/**
 * STYLIQUE CRM — Canonical Meeting Engine
 * 
 * ONE engine for all meeting operations across all surfaces.
 * Every meeting booking, completion, reschedule, and cancel goes through here.
 * 
 * Used by: Pipeline, Tasks, Calendar, CompanyDetailSheet, ExecutionFeed
 * 
 * MEETING OUTCOME ROUTING:
 *   interested        → meeting-completed + follow-up task (propose trial or next steps)
 *   propose_trial     → trial-proposed (enters approval chain)
 *   followup_later    → meeting-completed + dated follow-up task
 *   pending_internal  → meeting-completed + timed follow-up (client deciding)
 *   reschedule        → meeting-booked (stays, new date required)
 *   no_show           → meeting-booked + immediate retry task
 *   not_fit / lost    → closed-lost (archive everything)
 */

import type {
  Lead, CanonicalMeeting, MeetingOutcomeType, DealTask,
  MeetingNote, EntryFlow,
} from '@/types/crm';
import { recalculateNextAction, refreshTasksForStage } from '@/types/crm';
import { archiveStaleTasksForStage } from '@/engine/task-engine';
import type { StoreBridge } from '@/engine/action-executor';

// ═══════════════════════════════════════════════════════════
// BOOK MEETING — creates canonical meeting + updates lead
// ═══════════════════════════════════════════════════════════

export interface BookMeetingOptions {
  lead: Lead;
  meetingType: CanonicalMeeting['meeting_type'];
  meetingLink: string;
  scheduledAt: string;
  meetingSource?: CanonicalMeeting['meeting_source'];
  owner: string;
  performedBy: string;
}

export function bookMeeting(opts: BookMeetingOptions, bridge: StoreBridge): Lead {
  const { lead, meetingType, meetingLink, scheduledAt, meetingSource, owner, performedBy } = opts;
  const now = new Date().toISOString();

  const meeting: CanonicalMeeting = {
    meeting_id: crypto.randomUUID(),
    lead_id: lead.id,
    lead_key: lead.leadKey,
    owner,
    source_flow: lead.entry_flow || 'sdr_manual',
    meeting_type: meetingType,
    meeting_source: meetingSource || 'sdr_booked',
    scheduled_at: scheduledAt,
    meeting_link: meetingLink,
    status: 'scheduled',
    created_at: now,
    updated_at: now,
    sync_status: 'not_configured',
  };

  // Also create legacy MeetingNote for backward compat
  const legacyNote: MeetingNote = {
    id: meeting.meeting_id,
    date: scheduledAt,
    type: meetingType,
    link: meetingLink,
    summary: '',
    attendees: [lead.contactName],
    actionItems: [],
  };

  // Create prep task
  const prepTask: DealTask = {
    id: crypto.randomUUID(),
    title: `Prepare for meeting — ${lead.companyName}`,
    dueDate: scheduledAt,
    completed: false,
    assignedTo: owner,
    type: 'meeting-prep',
    autoGenerated: true,
    createdAt: now,
    priority: 'high',
    reason: `Meeting scheduled ${new Date(scheduledAt).toLocaleDateString()}`,
    stageFamily: 'meeting',
  };

  // Archive all prospecting/engagement tasks — meeting booked is a stage advance
  const archivedTasks = archiveStaleTasksForStage(lead.tasks || [], 'meeting-booked');

  let updated: Lead = {
    ...lead,
    stage: 'meeting-booked',
    meeting_status: 'booked',
    updatedAt: now,
    lastContactedAt: now,
    meetings: [...(lead.meetings || []), meeting],
    meetingNotes: [...(lead.meetingNotes || []), legacyNote],
    tasks: [...archivedTasks, prepTask],
  };

  const intel = recalculateNextAction(updated);
  updated = {
    ...updated,
    nextAction: intel.action,
    nextActionReason: intel.reason,
    nextActionUrgency: intel.urgency,
    nextFollowUp: intel.followUpDate,
  };

  bridge.saveCompany(updated);

  bridge.addActivity({
    id: crypto.randomUUID(),
    leadId: lead.id,
    type: 'meeting_booked',
    description: `📅 Meeting booked: ${lead.companyName} — ${meetingType} on ${new Date(scheduledAt).toLocaleDateString()}`,
    createdAt: now,
    createdBy: performedBy,
  });

  return updated;
}

// ═══════════════════════════════════════════════════════════
// COMPLETE MEETING — process outcome, update state, create next action
// ═══════════════════════════════════════════════════════════

export interface CompleteMeetingOptions {
  lead: Lead;
  meetingId: string;
  outcome: MeetingOutcomeType;
  summary: string;
  notes?: string;
  nextStep?: string;
  nextStepDate?: string;
  performedBy: string;
}

export function completeMeeting(opts: CompleteMeetingOptions, bridge: StoreBridge): Lead {
  const { lead, meetingId, outcome, summary, notes, nextStep, nextStepDate, performedBy } = opts;
  const now = new Date().toISOString();
  const tomorrow = new Date(Date.now() + 86400000).toISOString();
  const in2Days = new Date(Date.now() + 2 * 86400000).toISOString();

  // Update canonical meeting
  const meetings = (lead.meetings || []).map(m =>
    m.meeting_id === meetingId ? {
      ...m,
      status: outcomeToStatus(outcome),
      outcome,
      summary,
      notes,
      next_step: nextStep,
      next_step_date: nextStepDate,
      updated_at: now,
    } : m
  ) as CanonicalMeeting[];

  // Update legacy meetingNotes for backward compat
  const meetingNotes = (lead.meetingNotes || []).map(m =>
    m.id === meetingId ? {
      ...m,
      summary,
      outcome,
      nextStep,
    } : m
  );

  // Determine stage transition and next task based on outcome
  const { targetStage, task, meetingStatus } = getOutcomeTransition(lead, outcome, performedBy, now, tomorrow, in2Days, nextStepDate);

  // Archive ALL stale tasks from the meeting stage — clean slate
  const archivedTasks = archiveStaleTasksForStage(lead.tasks || [], targetStage);

  let updated: Lead = {
    ...lead,
    stage: targetStage,
    meeting_status: meetingStatus,
    updatedAt: now,
    lastContactedAt: now,
    meetings,
    meetingNotes,
    tasks: [
      ...archivedTasks,
      ...(task ? [task] : []),
    ],
  };

  const intel = recalculateNextAction(updated);
  updated = {
    ...updated,
    nextAction: intel.action,
    nextActionReason: intel.reason,
    nextActionUrgency: intel.urgency,
    nextFollowUp: intel.followUpDate,
  };

  bridge.saveCompany(updated);

  bridge.addActivity({
    id: crypto.randomUUID(),
    leadId: lead.id,
    type: 'meeting_completed',
    description: `🤝 Meeting outcome: ${OUTCOME_DESCRIPTIONS[outcome]}${summary ? ` — "${summary}"` : ''}`,
    createdAt: now,
    createdBy: performedBy,
    metadata: { outcome },
  });

  return updated;
}

// ═══════════════════════════════════════════════════════════
// RESCHEDULE MEETING
// ═══════════════════════════════════════════════════════════

export function rescheduleMeeting(
  lead: Lead,
  meetingId: string,
  newScheduledAt: string,
  newLink: string | undefined,
  performedBy: string,
  bridge: StoreBridge,
): Lead {
  const now = new Date().toISOString();

  const meetings = (lead.meetings || []).map(m =>
    m.meeting_id === meetingId ? {
      ...m,
      status: 'rescheduled' as const,
      scheduled_at: newScheduledAt,
      meeting_link: newLink || m.meeting_link,
      updated_at: now,
    } : m
  ) as CanonicalMeeting[];

  // Create new scheduled meeting
  const oldMeeting = lead.meetings?.find(m => m.meeting_id === meetingId);
  const newMeeting: CanonicalMeeting = {
    meeting_id: crypto.randomUUID(),
    lead_id: lead.id,
    lead_key: lead.leadKey,
    owner: oldMeeting?.owner || lead.assignedTo,
    source_flow: lead.entry_flow || 'sdr_manual',
    meeting_type: oldMeeting?.meeting_type || 'zoom',
    meeting_source: oldMeeting?.meeting_source || 'sdr_booked',
    scheduled_at: newScheduledAt,
    meeting_link: newLink || oldMeeting?.meeting_link || '',
    status: 'scheduled',
    created_at: now,
    updated_at: now,
    sync_status: 'not_configured',
  };

  // Legacy compat
  const legacyNote: MeetingNote = {
    id: newMeeting.meeting_id,
    date: newScheduledAt,
    type: newMeeting.meeting_type,
    link: newMeeting.meeting_link,
    summary: '',
    attendees: [lead.contactName],
    actionItems: [],
  };

  // Create new prep task
  const prepTask: DealTask = {
    id: crypto.randomUUID(),
    title: `Prepare for rescheduled meeting — ${lead.companyName}`,
    dueDate: newScheduledAt,
    completed: false,
    assignedTo: oldMeeting?.owner || lead.assignedTo,
    type: 'meeting-prep',
    autoGenerated: true,
    createdAt: now,
    priority: 'high',
    reason: `Meeting rescheduled to ${new Date(newScheduledAt).toLocaleDateString()}`,
    stageFamily: 'meeting',
  };

  // Archive old meeting tasks, keep the new prep
  const archivedTasks = archiveStaleTasksForStage(lead.tasks || [], 'meeting-booked');

  let updated: Lead = {
    ...lead,
    stage: 'meeting-booked',
    meeting_status: 'rescheduled',
    updatedAt: now,
    meetings: [...meetings, newMeeting],
    meetingNotes: [...(lead.meetingNotes || []), legacyNote],
    tasks: [...archivedTasks, prepTask],
  };

  const intel = recalculateNextAction(updated);
  updated = { ...updated, nextAction: intel.action, nextActionReason: intel.reason, nextActionUrgency: intel.urgency, nextFollowUp: intel.followUpDate };

  bridge.saveCompany(updated);

  bridge.addActivity({
    id: crypto.randomUUID(),
    leadId: lead.id,
    type: 'meeting_booked',
    description: `📅 Meeting rescheduled: ${lead.companyName} — ${new Date(newScheduledAt).toLocaleDateString()}`,
    createdAt: now,
    createdBy: performedBy,
  });

  return updated;
}

// ═══════════════════════════════════════════════════════════
// CANONICAL MEETING SELECTORS
// ═══════════════════════════════════════════════════════════

/** Get all canonical meetings across all leads, role-filtered.
 *  Falls back to legacy meetingNotes when canonical meetings[] is empty. */
export function getCanonicalMeetings(leads: Lead[], viewerRole: string, viewerUser: string): Array<{ meeting: CanonicalMeeting; lead: Lead }> {
  let filtered: Lead[];
  switch (viewerRole) {
    case 'sdr':
      filtered = leads.filter(l => l.assignedTo === viewerUser || l.assigned_sdr === viewerUser);
      break;
    case 'onboarding': {
      // Strict ownership: only this onboarding user's assigned leads.
      // Either the lead is in an onboarding-relevant stage, OR it has
      // an onboarding-sourced meeting THAT this user owns. We never
      // surface another onboarding user's check-ins.
      const onboardingStages = ['trial-proposed', 'trial-active', 'converted'];
      filtered = leads.filter(l => {
        const ownsLead = l.assigned_onboarding_owner === viewerUser;
        if (!ownsLead) return false;
        const inOnboardingStage = onboardingStages.includes(l.stage);
        const hasOnboardingMeeting = (l.meetings || []).some(
          m => m.meeting_source === 'onboarding_checkin'
        );
        return inOnboardingStage || hasOnboardingMeeting;
      });
      break;
    }
    case 'ceo':
    case 'coo':
      filtered = leads;
      break;
    default:
      filtered = [];
  }

  const results: Array<{ meeting: CanonicalMeeting; lead: Lead }> = [];

  for (const l of filtered) {
    // Use canonical meetings if available
    if (l.meetings && l.meetings.length > 0) {
      for (const m of l.meetings) {
        // Fix: past scheduled meetings → outcome required status
        const isPast = new Date(m.scheduled_at) < new Date();
        const corrected = { ...m };
        if (m.status === 'scheduled' && isPast && !m.outcome) {
          // Past meeting still marked scheduled = needs outcome
          corrected.notes = 'Awaiting outcome — add meeting result';
        }
        results.push({ meeting: corrected, lead: l });
      }
    } else if (l.meetingNotes && l.meetingNotes.length > 0) {
      // Fallback: convert legacy meetingNotes to CanonicalMeeting format
      for (const mn of l.meetingNotes) {
        const isPast = new Date(mn.date) < new Date();
        const hasSummary = !!mn.summary?.trim();
        // Past meetings without summary = awaiting outcome, NOT scheduled
        const derivedStatus: CanonicalMeeting['status'] = isPast
          ? (hasSummary ? 'completed' : 'scheduled')
          : 'scheduled';
        results.push({
          meeting: {
            meeting_id: mn.id,
            lead_id: l.id,
            lead_key: l.leadKey,
            owner: l.assignedTo,
            source_flow: l.entry_flow || 'sdr_manual',
            meeting_type: (mn.type as CanonicalMeeting['meeting_type']) || 'zoom',
            meeting_source: 'sdr_booked',
            scheduled_at: mn.date,
            meeting_link: mn.link || '',
            status: derivedStatus,
            outcome: isMeetingOutcomeType(mn.outcome) ? mn.outcome : undefined,
            summary: mn.summary,
            notes: isPast && !hasSummary ? 'Awaiting outcome — add meeting result' : undefined,
            created_at: mn.date,
            updated_at: mn.date,
            sync_status: 'not_configured',
          },
          lead: l,
        });
      }
    }
  }

  return results.sort((a, b) => new Date(a.meeting.scheduled_at).getTime() - new Date(b.meeting.scheduled_at).getTime());
}

/** Find the most recent meeting for a lead that needs outcome */
export function getMeetingNeedingOutcome(lead: Lead): CanonicalMeeting | null {
  const now = new Date();
  return (lead.meetings || [])
    .filter(m => m.status === 'scheduled' && new Date(m.scheduled_at) < now)
    .sort((a, b) => new Date(b.scheduled_at).getTime() - new Date(a.scheduled_at).getTime())[0] || null;
}

/** Find next upcoming meeting for a lead */
export function getNextScheduledMeeting(lead: Lead): CanonicalMeeting | null {
  const now = new Date();
  return (lead.meetings || [])
    .filter(m => m.status === 'scheduled' && new Date(m.scheduled_at) >= now)
    .sort((a, b) => new Date(a.scheduled_at).getTime() - new Date(b.scheduled_at).getTime())[0] || null;
}

// ═══════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════

const OUTCOME_DESCRIPTIONS: Record<MeetingOutcomeType, string> = {
  interested: 'Interested — continue discussion',
  propose_trial: 'Moved to Client Review',
  followup_later: 'Follow up later',
  not_fit: 'Not a fit — closing',
  lost: 'Lost — deal closed',
  pending_internal: 'Waiting on internal decision',
  pricing_discussion: 'Pricing discussion — send proposal',
  reschedule: 'Rescheduled',
  no_show: 'No show',
};

function isMeetingOutcomeType(value: string | undefined): value is MeetingOutcomeType {
  return !!value && value in OUTCOME_DESCRIPTIONS;
}

function outcomeToStatus(outcome: MeetingOutcomeType): CanonicalMeeting['status'] {
  switch (outcome) {
    case 'reschedule': return 'rescheduled';
    case 'no_show': return 'no_show';
    default: return 'completed';
  }
}

function getOutcomeTransition(
  lead: Lead,
  outcome: MeetingOutcomeType,
  owner: string,
  now: string,
  tomorrow: string,
  in2Days: string,
  nextStepDate?: string,
): { targetStage: Lead['stage']; task: DealTask | null; meetingStatus: Lead['meeting_status'] } {
  switch (outcome) {
    case 'interested':
      return {
        targetStage: 'meeting-completed',
        meetingStatus: 'completed',
        task: {
          id: crypto.randomUUID(),
          title: `Decision pending — ${lead.companyName}`,
          dueDate: tomorrow,
          completed: false,
          assignedTo: owner,
          type: 'follow-up',
          autoGenerated: true,
          createdAt: now,
          priority: 'critical',
          reason: 'Client interested after meeting',
          stageFamily: 'meeting',
        },
      };

    case 'propose_trial':
      return {
        targetStage: 'trial-proposed',
        meetingStatus: 'completed',
        task: {
          id: crypto.randomUUID(),
          title: `Client Review — ${lead.companyName}`,
          dueDate: tomorrow,
          completed: false,
          assignedTo: owner,
          type: 'follow-up',
          autoGenerated: true,
          createdAt: now,
          priority: 'critical',
          reason: 'Moved to Client Review',
          stageFamily: 'trial-prep',
        },
      };

    case 'followup_later':
      return {
        targetStage: 'meeting-completed',
        meetingStatus: 'completed',
        task: {
          id: crypto.randomUUID(),
          title: `Follow up with ${lead.contactName} — reconnect`,
          dueDate: nextStepDate || in2Days,
          completed: false,
          assignedTo: owner,
          type: 'follow-up',
          autoGenerated: true,
          createdAt: now,
          priority: 'medium',
          reason: 'Follow up later — agreed to reconnect',
          stageFamily: 'meeting',
        },
      };

    case 'no_show':
      return {
        targetStage: 'meeting-booked', // stays meeting-booked, needs reschedule
        meetingStatus: 'no-show',
        task: {
          id: crypto.randomUUID(),
          title: `Follow up NOW — ${lead.contactName} was a no-show`,
          dueDate: now,
          completed: false,
          assignedTo: owner,
          type: 'follow-up',
          autoGenerated: true,
          createdAt: now,
          priority: 'critical',
          reason: 'Client did not show up — call or email immediately',
          stageFamily: 'meeting',
        },
      };

    case 'reschedule':
      return {
        targetStage: 'meeting-booked',
        meetingStatus: 'rescheduled',
        task: {
          id: crypto.randomUUID(),
          title: `Confirm rescheduled meeting — ${lead.companyName}`,
          dueDate: tomorrow,
          completed: false,
          assignedTo: owner,
          type: 'follow-up',
          autoGenerated: true,
          createdAt: now,
          priority: 'medium',
          reason: 'Meeting rescheduled — confirm new date',
          stageFamily: 'meeting',
        },
      };

    case 'not_fit':
      return {
        targetStage: 'closed-lost',
        meetingStatus: 'completed',
        task: null,
      };

    case 'lost':
      return {
        targetStage: 'closed-lost',
        meetingStatus: 'completed',
        task: null,
      };

    case 'pending_internal':
      return {
        targetStage: 'meeting-completed',
        meetingStatus: 'completed',
        task: {
          id: crypto.randomUUID(),
          title: `Follow up on internal decision — ${lead.companyName}`,
          dueDate: nextStepDate || in2Days,
          completed: false,
          assignedTo: owner,
          type: 'follow-up',
          autoGenerated: true,
          createdAt: now,
          priority: 'high',
          reason: 'Waiting on internal decision — follow up to check progress',
          stageFamily: 'meeting',
        },
      };
  }
}
