/**
 * STYLIQUE CRM — Outcome Engine
 * 
 * Central intelligence: every outcome maps to a concrete next step.
 * No action completes silently. Every outcome creates the next task automatically.
 * 
 * RULES:
 * 1. Every outcome → exactly one next task or stage change
 * 2. Next task has: title, due date, owner, type, reason
 * 3. Manager-like language in prompts and reasons
 * 4. No dead states — system always knows what's next
 * 5. Old tasks ALWAYS archived on stage change
 * 6. Triggering task ALWAYS completed/archived on outcome
 * 7. Every outcome emits a CRMEvent via the event bus
 */

import type { Lead, DealTask, Activity, Stage } from '@/types/crm';
import { PLAN_PRICES, recalculateNextAction, refreshTasksForStage } from '@/types/crm';
import { uid } from '@/lib/store';
import { archiveStaleTasksForStage } from '@/engine/task-engine';
import { allowMutation } from '@/engine/hardening';
import { emitKPI, markContactReached } from '@/engine/kpi-integration';
import { emitCRMEvent, type CRMEventType } from '@/engine/event-bus';
import type { StoreBridge } from '@/engine/action-executor';
import { confirmPaymentAndRoll } from '@/engine/payment-ledger';
import type { TaskOutcome } from '@/components/TaskOutcomeDialog';
import type { MeetingOutcome } from '@/components/MeetingOutcomeDialog';
import type { PaymentOutcome } from '@/components/PaymentOutcomeDialog';
import type { CallOutcome } from '@/components/CallLogDialog';

/** Lightweight outreach outcome (formerly from apollo-sequence). */
type OutreachOutcome = 'no-response' | 'replied' | 'interested' | 'not-interested';

// ═══════════════════════════════════════════════════════════
// MANAGER PROMPTS — contextual "What happened?" language
// ═══════════════════════════════════════════════════════════

export function getManagerPrompt(actionType: string, companyName: string, contactName: string): string {
  switch (actionType) {
    case 'call': return `You called ${contactName}. What happened?`;
    case 'email': return `You emailed ${contactName}. Did they respond?`;
    case 'linkedin': return `You reached out on LinkedIn. What happened?`;
    case 'meeting': return `Meeting with ${companyName} finished. What was the result?`;
    case 'onboarding-task': return `You worked on ${companyName}'s setup. How did it go?`;
    case 'check-in': return `You checked in on ${companyName}. What did you find?`;
    case 'payment-action': return `Payment follow-up for ${companyName}. What's the status?`;
    case 'trial-action': return `Trial update for ${companyName}. What happened?`;
    case 'follow-up': return `You followed up with ${contactName}. Any response?`;
    default: return `You completed an action for ${companyName}. What happened?`;
  }
}

// ═══════════════════════════════════════════════════════════
// NEXT STEP DESCRIPTIONS — shown in toast after outcome
// ═══════════════════════════════════════════════════════════

export interface OutcomeResult {
  nextStepDescription: string;
  stageChange?: Stage;
  task?: Omit<DealTask, 'id' | 'createdAt'>;
  activityDescription: string;
}

// ═══════════════════════════════════════════════════════════
// CALL OUTCOME → NEXT STEP
// ═══════════════════════════════════════════════════════════

export function processCallOutcome(
  lead: Lead,
  outcome: CallOutcome,
  notes: string,
  performedBy: string,
  bridge: StoreBridge,
  callbackDate?: string,
): OutcomeResult {
  const now = new Date().toISOString();
  const tomorrow = new Date(Date.now() + 86400000).toISOString();
  const in2Days = new Date(Date.now() + 2 * 86400000).toISOString();

  let result: OutcomeResult;

  switch (outcome) {
    case 'interested':
      result = {
        nextStepDescription: `Book meeting with ${lead.contactName} — they're interested`,
        stageChange: lead.stage === 'new-lead' || lead.stage === 'contacted' || lead.stage === 'sdr-contacted' ? 'replied' : undefined,
        task: {
          title: `Book meeting with ${lead.contactName}`,
          dueDate: tomorrow,
          completed: false,
          assignedTo: lead.assignedTo,
          type: 'follow-up',
          autoGenerated: true,
          priority: 'critical',
          reason: 'Lead expressed interest on call — book meeting today',
          stageFamily: 'engagement',
        },
        activityDescription: `📞 Called ${lead.contactName} — interested. Next: book meeting`,
      };
      break;

    case 'no-answer':
      result = {
        nextStepDescription: `Try ${lead.contactName} again tomorrow via email or LinkedIn`,
        task: {
          title: `Follow up ${lead.companyName} — no answer on call`,
          dueDate: tomorrow,
          completed: false,
          assignedTo: lead.assignedTo,
          type: 'follow-up',
          autoGenerated: true,
          priority: 'high',
          reason: 'No answer on call — try different channel',
        },
        activityDescription: `📞 Called ${lead.contactName} — no answer`,
      };
      break;

    case 'not-interested':
      result = {
        nextStepDescription: `Close ${lead.companyName} — not interested`,
        stageChange: 'closed-lost',
        activityDescription: `📞 Called ${lead.contactName} — not interested. Deal closed.`,
      };
      break;

    case 'call-back-later':
      result = {
        nextStepDescription: `Callback scheduled for ${lead.contactName}`,
        task: {
          title: `Call back ${lead.contactName}`,
          dueDate: callbackDate ? new Date(callbackDate).toISOString() : in2Days,
          completed: false,
          assignedTo: lead.assignedTo,
          type: 'follow-up',
          autoGenerated: true,
          priority: 'high',
          reason: 'Client asked to call back later',
        },
        activityDescription: `📞 Called ${lead.contactName} — call back later`,
      };
      break;

    case 'answered':
    default:
      result = {
        nextStepDescription: `Continue conversation with ${lead.contactName}`,
        task: {
          title: `Follow up with ${lead.contactName} — continue conversation`,
          dueDate: in2Days,
          completed: false,
          assignedTo: lead.assignedTo,
          type: 'follow-up',
          autoGenerated: true,
          priority: 'medium',
          reason: 'Call connected — follow up to keep momentum',
        },
        activityDescription: `📞 Called ${lead.contactName} — connected${notes ? `: ${notes}` : ''}`,
      };
  }

  // KPI: emit call action
  emitKPI(performedBy, lead, lead.contactName, 'calls_made', 'call', outcome);

  // Apply changes
  applyOutcomeResult(lead, result, performedBy, `Call: ${outcome}`, 'call', notes, bridge);
  return result;
}

// ═══════════════════════════════════════════════════════════
// OUTREACH OUTCOME → NEXT STEP (email/linkedin/apollo)
// ═══════════════════════════════════════════════════════════

export function processOutreachOutcome(
  lead: Lead,
  outcome: OutreachOutcome,
  notes: string,
  performedBy: string,
  channel: 'email' | 'linkedin',
  bridge: StoreBridge,
): OutcomeResult {
  const tomorrow = new Date(Date.now() + 86400000).toISOString();

  let result: OutcomeResult;

  switch (outcome) {
    case 'interested':
      result = {
        nextStepDescription: `Book meeting with ${lead.contactName} now`,
        stageChange: 'replied',
        task: {
          title: `Book meeting with ${lead.contactName}`,
          dueDate: tomorrow,
          completed: false,
          assignedTo: lead.assignedTo,
          type: 'follow-up',
          autoGenerated: true,
          priority: 'critical',
          reason: 'Lead interested — capitalize immediately',
          stageFamily: 'engagement',
        },
        activityDescription: `✉️ ${channel === 'linkedin' ? 'LinkedIn' : 'Email'} — ${lead.contactName} interested`,
      };
      break;

    case 'replied':
      result = {
        nextStepDescription: `Respond to ${lead.contactName} — keep the conversation going`,
        stageChange: 'replied',
        task: {
          title: `Respond to ${lead.contactName}'s reply`,
          dueDate: new Date().toISOString(), // Today
          completed: false,
          assignedTo: lead.assignedTo,
          type: 'follow-up',
          autoGenerated: true,
          priority: 'critical',
          reason: 'Lead replied — respond same day',
          stageFamily: 'engagement',
        },
        activityDescription: `✉️ ${lead.contactName} replied via ${channel}`,
      };
      break;

    case 'not-interested':
      result = {
        nextStepDescription: `Close ${lead.companyName} — declined`,
        stageChange: 'closed-lost',
        activityDescription: `✉️ ${lead.contactName} not interested via ${channel}`,
      };
      break;

    case 'no-response':
    default:
      result = {
        nextStepDescription: 'Continue to next outreach step',
        activityDescription: `✉️ ${channel === 'linkedin' ? 'LinkedIn' : 'Email'} sent to ${lead.contactName} — no response yet`,
      };
      break;
  }

  // KPI: emit outreach action
  const kpiMetric = channel === 'email' ? 'emails_sent' : 'linkedin_actions';
  emitKPI(performedBy, lead, lead.contactName, kpiMetric, channel, outcome);
  if (outcome === 'replied' || outcome === 'interested') {
    emitKPI(performedBy, lead, lead.contactName, 'replies_received', channel, outcome);
  }

  applyOutcomeResult(lead, result, performedBy, `${channel}: ${outcome}`, channel, notes, bridge);
  return result;
}

// ═══════════════════════════════════════════════════════════
// MEETING OUTCOME → NEXT STEP
// ═══════════════════════════════════════════════════════════

export function processMeetingOutcome(
  lead: Lead,
  outcome: MeetingOutcome,
  summary: string,
  nextStep: string,
  performedBy: string,
  bridge: StoreBridge,
  nextStepDate?: string,
): OutcomeResult {
  const tomorrow = new Date(Date.now() + 86400000).toISOString();
  const in2Days = new Date(Date.now() + 2 * 86400000).toISOString();

  let result: OutcomeResult;

  switch (outcome) {
    case 'propose_trial':
      result = {
        nextStepDescription: `Moved to Client Review`,
        stageChange: 'trial-proposed',
        task: {
          title: `Client Review — ${lead.companyName}`,
          dueDate: tomorrow,
          completed: false,
          assignedTo: lead.assignedTo,
          type: 'follow-up',
          autoGenerated: true,
          priority: 'critical',
          reason: 'Moved to Client Review',
          stageFamily: 'trial-prep',
        },
        activityDescription: `Meeting: moved to Client Review for ${lead.companyName}`,
      };
      break;

    case 'interested':
      result = {
        nextStepDescription: nextStep || `Follow up with ${lead.contactName} on discussed items`,
        stageChange: 'meeting-completed',
        task: {
          title: nextStep || `Follow up — ${lead.companyName} interested, propose trial or next steps`,
          dueDate: tomorrow,
          completed: false,
          assignedTo: lead.assignedTo,
          type: 'follow-up',
          autoGenerated: true,
          priority: 'critical',
          reason: 'Meeting attended — interested, follow up on discussed items',
          stageFamily: 'meeting',
        },
        activityDescription: `🤝 Meeting: ${lead.companyName} — interested${summary ? ` — ${summary}` : ''}`,
      };
      break;

    case 'followup_later':
      result = {
        nextStepDescription: nextStep || `Follow up with ${lead.contactName} later`,
        stageChange: 'meeting-completed',
        task: {
          title: nextStep || `Follow up with ${lead.contactName} — reconnect`,
          dueDate: nextStepDate || in2Days,
          completed: false,
          assignedTo: lead.assignedTo,
          type: 'follow-up',
          autoGenerated: true,
          priority: 'medium',
          reason: 'Follow up later — agreed to reconnect',
          stageFamily: 'meeting',
        },
        activityDescription: `🤝 Meeting: ${lead.companyName} — follow up later${summary ? ` — ${summary}` : ''}`,
      };
      break;

    case 'reschedule':
      result = {
        nextStepDescription: `Meeting rescheduled — prepare again when new date set`,
        task: {
          title: `Confirm rescheduled meeting — ${lead.companyName}`,
          dueDate: in2Days,
          completed: false,
          assignedTo: lead.assignedTo,
          type: 'follow-up',
          autoGenerated: true,
          priority: 'medium',
          reason: 'Meeting rescheduled — confirm new date',
          stageFamily: 'meeting',
        },
        activityDescription: `🤝 Meeting rescheduled: ${lead.companyName}`,
      };
      break;

    case 'no_show':
      result = {
        nextStepDescription: `No-show — call or email ${lead.contactName} now`,
        task: {
          title: `Follow up now — ${lead.contactName} was a no-show`,
          dueDate: new Date().toISOString(),
          completed: false,
          assignedTo: lead.assignedTo,
          type: 'follow-up',
          autoGenerated: true,
          priority: 'critical',
          reason: 'No-show — call or email now',
          stageFamily: 'meeting',
        },
        activityDescription: `🤝 No-show: ${lead.contactName} missed meeting`,
      };
      break;

    case 'not_fit':
    case 'lost':
      result = {
        nextStepDescription: `Close lead — ${lead.companyName}`,
        stageChange: 'closed-lost',
        activityDescription: `🤝 Meeting: ${lead.companyName} — ${outcome === 'not_fit' ? 'not a fit' : 'lost'}`,
      };
      break;

    case 'pending_internal':
      result = {
        nextStepDescription: `Waiting on internal decision — ${lead.companyName}`,
        stageChange: 'internal-decision',
        task: {
          title: `Follow up on internal decision — ${lead.companyName}`,
          dueDate: nextStepDate || in2Days,
          completed: false,
          assignedTo: lead.assignedTo,
          type: 'follow-up',
          autoGenerated: true,
          priority: 'high',
          reason: 'Waiting on internal decision — follow up to check progress',
          stageFamily: 'meeting',
        },
        activityDescription: `🤝 Meeting: ${lead.companyName} — waiting on internal decision`,
      };
      break;

    case 'pricing_discussion':
      result = {
        nextStepDescription: `Send pricing proposal to ${lead.contactName}`,
        stageChange: 'pricing-discussion',
        task: {
          title: `Send pricing / proposal — ${lead.companyName}`,
          dueDate: new Date().toISOString(),
          completed: false,
          assignedTo: lead.assignedTo,
          type: 'follow-up',
          autoGenerated: true,
          priority: 'high',
          reason: 'Pricing discussion requested — send proposal today',
          stageFamily: 'meeting',
        },
        activityDescription: `🤝 Meeting: ${lead.companyName} — pricing discussion next`,
      };
      break;

    default:
      result = {
        nextStepDescription: 'Review meeting notes',
        activityDescription: `🤝 Meeting with ${lead.companyName}`,
      };
  }

  // Update meeting notes
  const updated = { ...lead };
  if (updated.meetingNotes?.length) {
    const lastMeeting = { ...updated.meetingNotes[updated.meetingNotes.length - 1] };
    lastMeeting.summary = summary;
    lastMeeting.outcome = outcome;
    lastMeeting.nextStep = nextStep;
    updated.meetingNotes = [...updated.meetingNotes.slice(0, -1), lastMeeting];
  }

  applyOutcomeResult(updated, result, performedBy, `Meeting: ${outcome}`, 'meeting', summary, bridge);

  // KPI: meeting-related emissions
  if (outcome === 'propose_trial') {
    emitKPI(performedBy, lead, lead.contactName, 'trials_proposed', 'meeting', outcome);
  }
  // Every meeting completion counts
  if (['interested', 'propose_trial', 'followup_later', 'pending_internal', 'pricing_discussion', 'not_fit', 'lost'].includes(outcome)) {
    emitKPI(performedBy, lead, lead.contactName, 'meetings_booked', 'meeting', outcome);
  }

  return result;
}

// ═══════════════════════════════════════════════════════════
// TASK OUTCOME → NEXT STEP (onboarding, check-in, conversion)
// ═══════════════════════════════════════════════════════════

export function processTaskOutcome(
  lead: Lead,
  outcome: TaskOutcome,
  notes: string,
  taskId: string | undefined,
  taskType: string,
  performedBy: string,
  bridge: StoreBridge,
): OutcomeResult {
  const tomorrow = new Date(Date.now() + 86400000).toISOString();
  const in2Days = new Date(Date.now() + 2 * 86400000).toISOString();
  const in3Days = new Date(Date.now() + 3 * 86400000).toISOString();

  let result: OutcomeResult;

  // Onboarding tasks (Muneeb)
  if (taskType === 'onboarding') {
    switch (outcome) {
      case 'completed':
        result = {
          nextStepDescription: `Setup complete — ${lead.companyName} trial can begin`,
          task: {
            title: `Day 2 check-in — ${lead.companyName}`,
            dueDate: in2Days,
            completed: false,
            assignedTo: 'muneeb',
            type: 'check-in',
            autoGenerated: true,
            priority: 'medium',
            reason: 'Account set up — check if client is using the product',
            stageFamily: 'trial',
          },
          activityDescription: `✅ Setup completed for ${lead.companyName}`,
        };
        break;
      case 'issue':
        result = {
          nextStepDescription: `Setup issue — resolve today for ${lead.companyName}`,
          task: {
            title: `Fix setup issue — ${lead.companyName}`,
            dueDate: new Date().toISOString(),
            completed: false,
            assignedTo: 'muneeb',
            type: 'onboarding',
            autoGenerated: true,
            priority: 'critical',
            reason: `Setup problem: ${notes || 'Issue reported — fix today'}`,
            stageFamily: 'trial',
          },
          activityDescription: `⚠️ Setup issue for ${lead.companyName}${notes ? `: ${notes}` : ''}`,
        };
        break;
      default:
        result = {
          nextStepDescription: 'Next onboarding step queued',
          activityDescription: `Onboarding update: ${lead.companyName} — ${outcome}`,
        };
    }
  }
  // Check-in tasks (Muneeb)
  else if (taskType === 'check-in') {
    switch (outcome) {
      case 'active':
        result = {
          nextStepDescription: `${lead.companyName} is active — schedule next check-in`,
          task: {
            title: `Next check-in — ${lead.companyName}`,
            dueDate: in3Days,
            completed: false,
            assignedTo: 'muneeb',
            type: 'check-in',
            autoGenerated: true,
            priority: 'medium',
            reason: 'Client is using product — periodic check-in',
            stageFamily: 'trial',
          },
          activityDescription: `✅ ${lead.companyName} — active usage confirmed`,
        };
        break;
      case 'not-using':
        result = {
          nextStepDescription: `${lead.companyName} not using — reach out now`,
          task: {
            title: `Call ${lead.contactName} — not using product`,
            dueDate: new Date().toISOString(),
            completed: false,
            assignedTo: 'muneeb',
            type: 'check-in',
            autoGenerated: true,
            priority: 'critical',
            reason: 'Low usage detected — call to help and re-engage',
            stageFamily: 'trial',
          },
          activityDescription: `⚠️ ${lead.companyName} — low/no usage detected`,
        };
        break;
      case 'issue':
        result = {
          nextStepDescription: `${lead.contactName} needs help — support call today`,
          task: {
            title: `Support call with ${lead.contactName}`,
            dueDate: new Date().toISOString(),
            completed: false,
            assignedTo: 'muneeb',
            type: 'check-in',
            autoGenerated: true,
            priority: 'critical',
            reason: `Client needs help: ${notes || 'Questions or issues reported'}`,
            stageFamily: 'trial',
          },
          activityDescription: `📞 ${lead.companyName} needs help${notes ? `: ${notes}` : ''}`,
        };
        break;
      default:
        result = {
          nextStepDescription: 'Next check-in scheduled',
          activityDescription: `Check-in: ${lead.companyName} — ${outcome}`,
        };
    }
  }
  // Conversion push (SDR)
  else if (taskType === 'conversion-push' || taskType === 'trial-end') {
    switch (outcome) {
      case 'interested':
        result = {
          nextStepDescription: `${lead.contactName} wants to convert — send payment details`,
          stageChange: 'payment-pending',
          task: {
            title: `Send payment details to ${lead.contactName}`,
            dueDate: new Date().toISOString(),
            completed: false,
            assignedTo: lead.assignedTo,
            type: 'payment',
            autoGenerated: true,
            priority: 'critical',
            reason: 'Client ready to pay — send details now',
            stageFamily: 'payment',
          },
          activityDescription: `🎯 ${lead.contactName} interested in converting`,
        };
        break;
      case 'not-now':
        result = {
          nextStepDescription: `${lead.contactName} needs time — follow up in 2 days`,
          task: {
            title: `Follow up conversion — ${lead.companyName}`,
            dueDate: in2Days,
            completed: false,
            assignedTo: lead.assignedTo,
            type: 'conversion-push',
            autoGenerated: true,
            priority: 'high',
            reason: 'Client not ready yet — follow up soon',
            stageFamily: 'trial',
          },
          activityDescription: `⏳ ${lead.contactName} — not ready to convert yet`,
        };
        break;
      case 'no-answer':
        result = {
          nextStepDescription: `Try ${lead.contactName} again tomorrow`,
          task: {
            title: `Call ${lead.contactName} again — conversion follow-up`,
            dueDate: tomorrow,
            completed: false,
            assignedTo: lead.assignedTo,
            type: 'conversion-push',
            autoGenerated: true,
            priority: 'high',
            reason: 'Could not reach — try again tomorrow',
            stageFamily: 'trial',
          },
          activityDescription: `📞 ${lead.contactName} — no answer on conversion call`,
        };
        break;
      case 'lost':
        result = {
          nextStepDescription: `${lead.companyName} lost — deal closed`,
          stageChange: 'closed-lost',
          activityDescription: `❌ ${lead.companyName} — will not convert. Deal closed.`,
        };
        break;
      default:
        result = {
          nextStepDescription: 'Next step queued',
          activityDescription: `Conversion update: ${lead.companyName} — ${outcome}`,
        };
    }
  }
  // Generic follow-up — route by stage context
  else {
    switch (outcome) {
      case 'completed':
        result = {
          nextStepDescription: 'Task completed — next step queued',
          activityDescription: `✅ Task completed: ${lead.companyName}`,
        };
        break;
      case 'issue':
        result = {
          nextStepDescription: `Issue found — follow up on ${lead.companyName}`,
          task: {
            title: `Resolve issue — ${lead.companyName}`,
            dueDate: new Date().toISOString(),
            completed: false,
            assignedTo: performedBy,
            type: 'follow-up',
            autoGenerated: true,
            priority: 'high',
            reason: notes || 'Issue reported — resolve today',
          },
          activityDescription: `⚠️ Issue: ${lead.companyName}${notes ? ` — ${notes}` : ''}`,
        };
        break;
      default:
        result = {
          nextStepDescription: 'Next step queued',
          activityDescription: `Task update: ${lead.companyName} — ${outcome}`,
        };
    }
  }

  // Complete the specific task FIRST
  const updated = { ...lead };
  if (taskId) {
    updated.tasks = (updated.tasks || []).map(t =>
      t.id === taskId
        ? { ...t, completed: true, completedAt: new Date().toISOString(), completedBy: performedBy, state: 'completed' as const }
        : t
    );
  }

  applyOutcomeResult(updated, result, performedBy, `${taskType}: ${outcome}`, 'system', notes, bridge);
  return result;
}

// ═══════════════════════════════════════════════════════════
// PAYMENT OUTCOME → NEXT STEP
// ═══════════════════════════════════════════════════════════

export function processPaymentOutcome(
  lead: Lead,
  outcome: PaymentOutcome,
  notes: string,
  performedBy: string,
  bridge: StoreBridge,
): OutcomeResult {
  const in3Days = new Date(Date.now() + 3 * 86400000).toISOString();

  let result: OutcomeResult;

  switch (outcome) {
    case 'paid':
      result = {
        nextStepDescription: `${lead.companyName} is now a paying client!`,
        stageChange: 'converted',
        activityDescription: `💰 Payment received — ${lead.companyName} converted to client`,
      };
      break;
    case 'reminder-sent':
      result = {
        nextStepDescription: `Reminder sent — follow up in 3 days if no payment`,
        task: {
          title: `Follow up payment — ${lead.companyName}`,
          dueDate: in3Days,
          completed: false,
          assignedTo: performedBy,
          type: 'payment',
          autoGenerated: true,
          priority: 'high',
          reason: 'Payment reminder sent — follow up if not received',
          stageFamily: 'payment',
        },
        activityDescription: `📨 Payment reminder sent to ${lead.contactName}`,
      };
      break;
    case 'requested-time':
      result = {
        nextStepDescription: `Client needs more time — check back in 3 days`,
        task: {
          title: `Check payment status — ${lead.companyName}`,
          dueDate: in3Days,
          completed: false,
          assignedTo: performedBy,
          type: 'payment',
          autoGenerated: true,
          priority: 'medium',
          reason: 'Client requested more time — do not let this slip',
          stageFamily: 'payment',
        },
        activityDescription: `⏳ ${lead.contactName} requested more time for payment`,
      };
      break;
    case 'lost':
      result = {
        nextStepDescription: `${lead.companyName} — deal lost`,
        stageChange: 'closed-lost',
        activityDescription: `❌ ${lead.companyName} will not pay — deal closed`,
      };
      break;
    default:
      result = {
        nextStepDescription: 'Payment status updated',
        activityDescription: `Payment update: ${lead.companyName}`,
      };
  }

  // Payment-specific state updates
  const updated = { ...lead };
  if (outcome === 'paid') {
    // Drive monthly billing through the first-class ledger.
    // confirmPaymentAndRoll: marks current entry paid, creates next month
    // entry, advances nextPaymentDate, promotes proposed → active deal.
    const rolled = confirmPaymentAndRoll(updated, performedBy, undefined, notes);
    Object.assign(updated, rolled);
  } else if (outcome === 'reminder-sent') {
    updated.lastContactedAt = new Date().toISOString();
  }

  applyOutcomeResult(updated, result, performedBy, `Payment: ${outcome}`, 'system', notes, bridge);

  // KPI: payment confirmed
  if (outcome === 'paid') {
    emitKPI(performedBy, lead, lead.contactName, 'payments_confirmed', 'system', outcome);
  }

  return result;
}

// ═══════════════════════════════════════════════════════════
// CORE: Apply outcome result to lead — ATOMIC TRANSACTION
// Updates: stage, tasks (archive old + create new), timeline, intelligence
// ═══════════════════════════════════════════════════════════

function applyOutcomeResult(
  lead: Lead,
  result: OutcomeResult,
  performedBy: string,
  actionLabel: string,
  channel: string,
  notes: string,
  bridge: StoreBridge,
  /** Which contact was actually acted upon — defaults to primary */
  targetContactName?: string,
) {
  // Duplicate-submit protection
  if (!allowMutation(lead.id, actionLabel)) {
    console.warn(`[OutcomeEngine] Blocked duplicate: ${actionLabel} on ${lead.companyName}`);
    return;
  }
  const now = new Date().toISOString();
  const updated = { ...lead, updatedAt: now };

  // Mark the ACTUAL contact as reached (not always primary)
  const contactName = targetContactName || lead.contactName;
  if (contactName && ['call', 'email', 'linkedin', 'meeting'].includes(channel)) {
    updated.contacts = markContactReached(updated, contactName);
    updated.contactsReachedCount = (updated.contacts || []).filter(c => c.reached).length;
  }

  // Stage change — archive ALL stale tasks from previous stage
  if (result.stageChange) {
    updated.tasks = archiveStaleTasksForStage(updated.tasks || [], result.stageChange);
    updated.stage = result.stageChange;
  }

  // Cancel any existing auto-generated pending tasks of the SAME type
  // before adding the new one — prevents duplicates.
  if (result.task) {
    updated.tasks = (updated.tasks || []).map(t => {
      if (t.completed || t.state === 'cancelled') return t;
      // Cancel same-type auto tasks to prevent duplicates
      if (t.autoGenerated && t.type === result.task!.type) {
        return {
          ...t,
          state: 'cancelled' as const,
          completed: true,
          cancelledAt: now,
          cancelReason: `Replaced by new task after outcome: ${actionLabel}`,
        };
      }
      return t;
    });

    const newTask: DealTask = {
      ...result.task,
      id: uid(),
      createdAt: now,
      stageFamily: result.task.stageFamily || (result.stageChange
        ? getStageFamily(result.stageChange)
        : getStageFamily(lead.stage)),
    };
    updated.tasks = [...updated.tasks, newTask];
  } else if (!result.stageChange) {
    // No new task AND no stage change — still archive the CURRENT triggering task
    // (the action was completed, so any matching open task should be closed)
    updated.tasks = (updated.tasks || []).map(t => {
      if (t.completed || t.state === 'cancelled') return t;
      // Complete auto tasks matching this action's channel/type
      if (t.autoGenerated && !t.completed) {
        const actionLower = actionLabel.toLowerCase();
        const titleLower = (t.title || '').toLowerCase();
        // Close tasks whose title matches the logged action
        if (
          (actionLower.includes('call') && titleLower.includes('call')) ||
          (actionLower.includes('meeting') && (titleLower.includes('meeting') || titleLower.includes('prep'))) ||
          (actionLower.includes('payment') && titleLower.includes('payment'))
        ) {
          return {
            ...t,
            completed: true,
            completedAt: now,
            completedBy: performedBy,
            state: 'completed' as const,
          };
        }
      }
      return t;
    });
  }

  // Log completion — with contact-level tracking
  updated.actionCompletions = [
    ...(updated.actionCompletions || []),
    { id: uid(), action: actionLabel, completedAt: now, completedBy: performedBy, channel, notes, contactName },
  ];

  // Recalculate intelligence
  const intel = recalculateNextAction(updated);
  updated.nextAction = intel.action;
  updated.nextActionReason = intel.reason;
  updated.nextActionUrgency = intel.urgency;
  updated.nextFollowUp = intel.followUpDate;

  // Persist — ONE atomic save
  bridge.saveCompany(updated);
  bridge.addActivity({
    id: uid(),
    leadId: lead.id,
    type: channel === 'call' ? 'call' : channel === 'email' ? 'email' : channel === 'meeting' ? 'meeting' : 'action-completed',
    description: result.activityDescription,
    createdAt: now,
    createdBy: performedBy,
  });

  // Emit canonical event — all subscribers (toast, KPI dashboards, etc.) react
  // Use specific canonical event types instead of generic legacy types
  const canonicalEventType: CRMEventType = (() => {
    if (channel === 'call') return 'outreach.call_made';
    if (channel === 'meeting') {
      if (result.stageChange === 'trial-proposed') return 'trial.proposed';
      if (result.stageChange === 'internal-decision') return 'lead.stage_changed';
      if (result.stageChange === 'pricing-discussion') return 'lead.stage_changed';
      return 'meeting.outcome_logged';
    }
    if (result.stageChange === 'converted') return 'client.converted';
    if (result.stageChange === 'payment-pending') return 'payment.pending';
    if (result.stageChange === 'closed-lost') return 'lead.closed';
    if (result.stageChange === 'trial-proposed') return 'trial.proposed';
    if (result.stageChange === 'trial-active') return 'trial.activated';
    if (channel === 'email') return 'outreach.email_sent';
    if (channel === 'linkedin') return 'outreach.linkedin_sent';
    return 'lead.stage_changed';
  })();
  emitCRMEvent(canonicalEventType, performedBy, result.activityDescription, {
    leadId: lead.id,
    companyName: lead.companyName,
    contactName: lead.contactName,
    nextStep: result.nextStepDescription,
    metadata: { stageChange: result.stageChange, actionLabel },
  });
}

/** Helper to get stage family for task tagging */
function getStageFamily(stage: string): string {
  const map: Record<string, string> = {
    'new-lead': 'prospecting', 'contacted': 'prospecting', 'lead-added': 'prospecting',
    'sdr-new-lead': 'prospecting', 'sdr-contacted': 'prospecting',
    'outreach-1': 'prospecting', 'outreach-2': 'prospecting', 'outreach-3': 'prospecting',
    'sequence-completed': 'prospecting', 'new-inquiry': 'prospecting',
    'replied': 'engagement', 'sdr-replied': 'engagement',
    'awaiting-sdr': 'engagement', 'qualified': 'engagement',
    'meeting-booked': 'meeting', 'meeting-completed': 'meeting',
    'trial-proposed': 'trial-prep',
    'trial-active': 'trial',
    'payment-pending': 'payment',
    'converted': 'customer',
    'closed-lost': 'closed',
  };
  return map[stage] || 'prospecting';
}
