/**
 * STYLIQUE CRM — Core Types V2
 * 2-Flow Architecture: Inbound, SDR Manual
 * Shared Commercial Lifecycle post-meeting/trial/payment
 */

// ─── Entry Flow & Source ─────────────────────────────────

export type EntryFlow = 'inbound' | 'sdr_manual';
export type InboundType = 'ai_inbound' | 'direct_book_demo' | 'manual_inbound' | null;
export type SourceDetail =
  | 'instagram' | 'google_search' | 'linkedin_evaboot'
  | 'website_demo' | 'website_form' | 'whatsapp'
  | 'instagram_dm' | 'linkedin_dm' | 'email_inbound'
  | 'ai_chatbot' | 'referral' | 'manual_import' | 'other';
export type ActionOwner = 'sdr' | 'onboarding' | 'leadership';

// ─── Pipeline (maps 1:1 to flows) ───────────────────────

export type Pipeline = 'outbound-sdr' | 'inbound';

// ─── Stages ──────────────────────────────────────────────

export type Stage =
  // Legacy AI Outbound stages (dead — migrated on read in src/lib/store.ts).
  // Retained in the union so historical engine branches still type-check.
  | 'ai-new-lead' | 'pending-enrichment' | 'pending-apollo' | 'ready-for-outreach'
  | 'email-sent-d0' | 'followup-1-d3' | 'followup-2-d7' | 'followup-3-d14' | 'round4-d17'
  // Inbound stages
  | 'inbound-new' | 'inbound-qualified' | 'inbound-awaiting-sdr'
  | 'inbound-disqualified'
  // SDR Manual stages
  | 'sdr-new-lead' | 'sdr-contacted' | 'sdr-replied'
  // Shared Commercial Lifecycle stages
  | 'meeting-booked' | 'meeting-completed'
  | 'internal-decision' | 'pricing-discussion'
  | 'trial-proposed' | 'trial-active'
  | 'payment-pending' | 'converted' | 'closed-lost'
  | 'unsubscribed' | 'cold-no-response'
  // Legacy compat (mapped internally)
  | 'new-lead' | 'contacted' | 'replied' | 'lead-added'
  | 'outreach-1' | 'outreach-2' | 'outreach-3'
  | 'sequence-completed' | 'awaiting-sdr'
  | 'new-inquiry' | 'qualified';

export type Platform = 'shopify' | 'woocommerce' | 'custom';
export type SubscriptionPlan = 'lite' | 'starter' | 'growth' | 'enterprise' | 'custom';
/** First-class commercial currency. PKR is default for the local market. */
export type Currency = 'PKR' | 'USD' | 'GBP' | 'AED';
/** Region the client operates in (drives reporting, NOT billing). */
export type Region = 'PK' | 'US' | 'UK' | 'UAE' | 'OTHER';
export type SubscriptionStatus = 'active' | 'pending' | 'cancelled';
export type PaymentStatus = 'pending' | 'paid' | 'overdue' | 'at-risk';
export type LeadSource = 'instagram' | 'google' | 'linkedin' | 'referral' | 'website' | 'other';
export type LeadTier = 'tier-1' | 'tier-2' | 'tier-3';
export type LeadPriority = 'high' | 'medium' | 'low';
export type SmartleadStatus = 'assigned' | 'opened' | 'replied' | 'no-response' | 'completed';
export type TaskPriority = 'critical' | 'high' | 'medium' | 'low';
export type TaskState = 'pending' | 'completed' | 'cancelled';

export type OutreachStatus = 'not-started' | 'in-progress' | 'completed' | 'paused';
export type EnrichmentStatus = 'not-started' | 'in-progress' | 'completed' | 'failed';
export type MeetingStatus = 'none' | 'booked' | 'completed' | 'no-show' | 'rescheduled';
export type TrialStatus = 'none' | 'proposed' | 'setup-pending' | 'active' | 'ending' | 'ended' | 'converted' | 'lost';
export type CloseReason = 'not-interested' | 'no-response' | 'unsubscribed' | 'bad-fit' | 'competitor' | 'budget' | 'timing' | 'other' | null;

export interface DealTask {
  id: string;
  title: string;
  dueDate: string;
  completed: boolean;
  completedAt?: string;
  completedBy?: string;
  assignedTo: string;
  type: 'follow-up' | 'onboarding' | 'check-in' | 'conversion-push' | 'trial-end' | 'general' | 'outreach' | 'meeting-prep' | 'meeting-summary' | 'payment';
  autoGenerated?: boolean;
  createdAt: string;
  priority?: TaskPriority;
  reason?: string;
  stageFamily?: string;
  state?: TaskState;
  cancelledAt?: string;
  cancelReason?: string;
}

export interface StoreCredentials {
  username: string;
  password: string;
  loginUrl?: string;
  installationNotes?: string;
  specialInstructions?: string;
  supportContact?: string;
  addedBy?: string;
  addedAt?: string;
}

export interface ActionCompletion {
  id: string;
  action: string;
  completedAt: string;
  completedBy: string;
  channel?: string;
  notes?: string;
  /** Which specific contact was acted upon — enables contact-level tracking */
  contactName?: string;
}

export interface LeadIntelligence {
  source?: LeadSource;
  instagramFollowers?: number;
  estimatedTraffic?: string;
  tier?: LeadTier;
}

export interface MeetingNote {
  id: string;
  date: string;
  type: 'zoom' | 'google-meet' | 'teams' | 'other';
  link?: string;
  summary: string;
  outcome?: string;
  nextStep?: string;
  attendees: string[];
  actionItems: string[];
}

// ─── Canonical Meeting Object ────────────────────────────

export type MeetingStatus_Canonical = 'scheduled' | 'completed' | 'rescheduled' | 'no_show' | 'cancelled';

export type MeetingOutcomeType =
  | 'interested'
  | 'propose_trial'
  | 'followup_later'
  | 'not_fit'
  | 'lost'
  | 'pending_internal'
  | 'pricing_discussion'
  | 'reschedule'
  | 'no_show';

export const MEETING_OUTCOME_LABELS: Record<MeetingOutcomeType, string> = {
  interested: 'Interested',
  propose_trial: 'Interested',
  followup_later: 'Follow-up needed',
  not_fit: 'Not interested',
  lost: 'Not interested',
  pending_internal: 'Follow-up needed',
  pricing_discussion: 'Follow-up needed',
  reschedule: 'Rescheduled',
  no_show: 'No show',
};

export interface CanonicalMeeting {
  meeting_id: string;
  lead_id: string;
  lead_key?: string;
  owner: string;
  source_flow: EntryFlow;
  meeting_type: 'zoom' | 'google-meet' | 'teams' | 'other';
  meeting_source: 'sdr_booked' | 'inbound_demo' | 'onboarding_checkin' | 'conversion_call' | 'other';
  scheduled_at: string;
  meeting_link: string;
  status: MeetingStatus_Canonical;
  outcome?: MeetingOutcomeType;
  summary?: string;
  notes?: string;
  next_step?: string;
  next_step_date?: string;
  created_at: string;
  updated_at: string;
  /** External calendar event ID for Teams/Outlook sync */
  external_calendar_id?: string;
  sync_status?: 'synced' | 'pending' | 'failed' | 'not_configured';
}

/**
 * Legacy lead entry source. 'ai-outbound' is compatibility-only for
 * legacy localStorage records (migrated to 'sdr-manual' in src/lib/store.ts).
 * Do not use 'ai-outbound' for new logic.
 */
export type LeadEntrySource = 'ai-outbound' | 'sdr-manual' | 'inbound' | 'referral';

// ─── Priority / Engagement Tier ──────────────────────────
export type PriorityTier = 'cold' | 'warm' | 'hot' | 'replied' | 'meeting-booked' | 'trial-active' | 'payment-pending';
export type EngagementStatus = 'none' | 'opened' | 'clicked' | 'replied' | 'bounced';

// ─── Reply Classification ──
export type ReplyClassification =
  | 'interested'
  | 'not_interested'
  | 'later'
  | 'wrong_person'
  | 'out_of_office'
  | 'unsubscribe'
  | 'bounce'
  | 'neutral_unclear';

export const REPLY_CLASSIFICATION_LABELS: Record<ReplyClassification, string> = {
  interested: 'Interested',
  not_interested: 'Not Interested',
  later: 'Follow Up Later',
  wrong_person: 'Wrong Person',
  out_of_office: 'Out of Office',
  unsubscribe: 'Unsubscribe Request',
  bounce: 'Bounced',
  neutral_unclear: 'Neutral / Unclear',
};

/** Contact record — child of a brand/company */
export interface BrandContact {
  id: string;
  name: string;
  role?: string;
  email?: string;
  phone?: string;
  linkedin?: string;
  instagram?: string;
  /** Whether this contact has been reached via valid outreach */
  reached?: boolean;
  /** Timestamp of first valid outreach */
  firstReachedAt?: string;
}

/** Secondary contact details (legacy compat — prefer contacts[] array) */
export interface SecondaryContact {
  name: string;
  role?: string;
  email?: string;
  phone?: string;
  linkedin?: string;
  instagram?: string;
}

export interface Lead {
  id: string;
  companyName: string;
  contactName: string;
  contactRole?: string;
  contactEmail: string;
  contactPhone?: string;
  website?: string;
  instagram?: string;
  linkedin?: string;
  /** Secondary contact — full structured fields (legacy compat) */
  secondaryContact?: SecondaryContact;
  /** All contacts under this brand — canonical contact list */
  contacts?: BrandContact[];
  /** Number of unique contacts reached (KPI helper) */
  contactsReachedCount?: number;
  pipeline: Pipeline;
  stage: Stage;
  assignedTo: string;
  platform?: Platform;
  nextAction?: string;
  nextActionReason?: string;
  nextActionUrgency?: 'now' | 'today' | 'upcoming';
  nextFollowUp?: string;
  notes: string;
  createdAt: string;
  updatedAt: string;
  lastContactedAt?: string;
  // ─── Timing Memory ────────────────────────────────
  lastEmailAt?: string;
  lastLinkedinAt?: string;
  lastCallAt?: string;
  lastReplyAt?: string;
  // ─── 3-Flow Identity ──────────────────────────────
  /** Primary flow: inbound | sdr_manual */
  entry_flow?: EntryFlow;
  /** Inbound sub-type (only when entry_flow = 'inbound') */
  inbound_type?: InboundType;
  /** Granular source detail */
  source_detail?: SourceDetail;
  /** Who currently owns the next action */
  action_owner?: ActionOwner;
  /** Who owns this record */
  record_owner?: string;
  /** Assigned SDR */
  assigned_sdr?: string;
  /** Assigned onboarding owner */
  assigned_onboarding_owner?: string;
  /** Outreach status (legacy field — kept for compatibility) */
  outreach_status?: OutreachStatus;
  /** Enrichment status */
  enrichment_status?: EnrichmentStatus;
  /** Engagement status (opens/clicks/replies) */
  engagement_status?: EngagementStatus;
  /** Meeting status */
  meeting_status?: MeetingStatus;
  /** Trial status */
  trial_status?: TrialStatus;
  /** Close reason */
  close_reason?: CloseReason;
  /** Last verified engagement event */
  last_verified_event?: string;
  /** Timestamp of last verified event */
  last_verified_event_at?: string;
  /** Priority/hotness tier */
  priority_tier?: PriorityTier;
  /** Next action due date */
  next_action_due_at?: string;
  // ─── SDR Email Identity ────────────────────────────
  /** Outlook/mailbox used for sending */
  sdr_sending_mailbox?: string;
  /** Reply mailbox if different */
  sdr_reply_mailbox?: string;
  // ─── Twilio Call Identity ──────────────────────────
  /** Twilio number used for calls on this lead */
  twilio_number_used?: string;
  /** Call log entries */
  call_log?: CallLogEntry[];
  /** SDR email log entries */
  email_log?: EmailLogEntry[];
  // ─── Trial & Payment ──────────────────────────────
  trialStartDate?: string;
  trialEndDate?: string;
  trialManualOverride?: boolean;
  /** Pilot naming for the current business flow. Kept alongside legacy trial fields for migration compatibility. */
  pilotStartDate?: string;
  pilotEndDate?: string;
  pilotDecisionAt?: string;
  pilotDecisionBy?: string;
  pilotDecision?: 'contract' | 'lost';
  clientReviewApprovedAt?: string;
  clientReviewApprovedBy?: string;
  paymentVerifiedAt?: string;
  paymentVerifiedBy?: string;
  contractSignedAt?: string;
  contractStartDate?: string;
  contractEndDate?: string;
  subscriptionPlan?: SubscriptionPlan;
  subscriptionStatus?: SubscriptionStatus;
  subscriptionStartDate?: string;
  nextPaymentDate?: string;
  paymentStatus?: PaymentStatus;
  paymentReceivedAt?: string;
  // ─── First-class commercial model ──────────────────
  // PROPOSED terms — set by CEO/COO during Conversion Pending / CEO Review.
  proposed_package?: SubscriptionPlan;
  proposed_currency?: Currency;
  proposed_value?: number;
  // ACTIVE client billing truth — frozen on first 'paid' confirmation.
  // Once a record becomes a real client these are the source of truth and
  // must NOT silently follow proposed_* changes.
  active_package?: SubscriptionPlan;
  active_currency?: Currency;
  active_value?: number;
  /** Operating region — independent from currency. */
  region?: Region;
  /** Per-client payment ledger — drives Payments page + history. */
  paymentLedger?: PaymentLedgerEntry[];
  /** Client / SDR claims payment was made — leadership must verify (Awaiting Confirmation). */
  paymentClaimedAt?: string;
  paymentClaimedBy?: string;
  paymentClaimNotes?: string;
  extraTryOns?: number;
  /** Enterprise add-on: in-store installation */
  inStoreInstallation?: boolean;
  /** Lite plan region constraint (Pakistan only) */
  planRegion?: string;
  tasks: DealTask[];
  priority?: LeadPriority;
  intelligence?: LeadIntelligence;
  meetingNotes?: MeetingNote[];
  /** Canonical meetings — source of truth for calendar */
  meetings?: CanonicalMeeting[];
  smartleadStatus?: SmartleadStatus;
  storeCredentials?: string;
  credentials?: StoreCredentials;
  credentialsAddedBy?: string;
  approvedBy?: string;
  actionCompletions?: ActionCompletion[];
  // ─── Unified Pipeline Identity ────────────────────
  leadKey?: string;
  entrySource?: LeadEntrySource;
  previousPipeline?: Pipeline;
  // ─── Sync & Detection ─────────────────────────────
  /** Sync status for external integrations */
  sync_status?: 'synced' | 'pending' | 'failed' | 'not_configured';
  sync_retry_count?: number;
  sync_last_attempt_at?: string;
  sync_last_success_at?: string;
  sync_last_error?: string;
  /** Reply detection status */
  reply_detection_status?: 'none' | 'detected' | 'confirmed' | 'false_positive';
  /** Classified reply type */
  reply_classification?: ReplyClassification;
  /** Whether outreach is blocked (e.g., manual_research_required with no valid email) */
  outreach_blocked?: boolean;
  outreach_blocked_reason?: string;
  // ─── Post-Trial Decision ───────────────────────────
  /** Explicit decision after trial ended.
   *  'continuing' → moves into payment window
   *  'declined'   → moves to Ended/Lost
   *  'extend'     → trial extended (new dates)
   *  undefined    → still awaiting decision (within grace) or auto-resolved past grace */
  postTrialDecision?: 'continuing' | 'declined' | 'extend';
  postTrialDecisionAt?: string;
  postTrialDecisionBy?: string;
  // ─── Onboarding Done & Verified ──────────────────
  /** Set when onboarding marks the client done & verified — record becomes Active Client. */
  onboardingDoneAt?: string;
  onboardingDoneBy?: string;
  // ─── Loss / Rejection Reason ─────────────────────
  /** Reason captured when a deal is rejected at Client Review or otherwise marked Closed Lost. */
  lossReason?: string;
  lossReasonAt?: string;
  lossReasonBy?: string;
}

// ─── Call Log Entry ──────────────────────────────────────

export interface CallLogEntry {
  id: string;
  timestamp: string;
  sdrOwner: string;
  twilioNumber: string;
  contactPhone: string;
  duration?: number;
  outcome: 'connected_interested' | 'connected_followup' | 'no_answer' | 'wrong_person' | 'not_interested' | 'call_again' | 'booked_meeting';
  notes?: string;
  nextAction?: string;
}

// ─── Email Log Entry ─────────────────────────────────────

export interface EmailLogEntry {
  id: string;
  timestamp: string;
  sdrOwner: string;
  apolloIdentity?: string;
  sendingMailbox: string;
  replyMailbox?: string;
  subject: string;
  bodyPreview?: string;
  direction: 'outbound' | 'inbound';
  replyStatus?: 'none' | 'replied' | 'bounced';
  threadRef?: string;
}

// ─── SDR Identity Config ─────────────────────────────────

export interface SDRIdentityConfig {
  sdrId: string;
  apolloIdentity?: string;
  outlookMailbox?: string;
  replyMailbox?: string;
  twilioNumbers: string[];
  defaultTwilioNumber?: string;
}

export type ActivityType =
  | 'stage-change' | 'note' | 'email' | 'call' | 'meeting' | 'task'
  | 'payment' | 'trial-start' | 'conversion' | 'action-completed' | 'handoff'
  // Unified timeline events — immutable event log
  | 'lead_scraped' | 'lead_upserted' | 'enrichment_started' | 'enrichment_updated'
  | 'classified' | 'assigned'
  | 'initial_email_sent' | 'followup_1_sent' | 'followup_2_sent' | 'followup_3_sent'
  | 'email_opened' | 'reply_detected' | 'unsubscribed'
  | 'handoff_to_sdr' | 'sequence_completed_warm' | 'sequence_completed_cold'
  | 'sdr_email_sent' | 'sdr_email_reply'
  | 'twilio_call_made' | 'twilio_call_outcome_logged'
  | 'linkedin_outreach_logged' | 'instagram_outreach_logged'
  | 'meeting_booked' | 'meeting_completed'
  | 'trial_proposed' | 'trial_activated' | 'trial_ended'
  | 'payment_confirmed' | 'payment_reminder_sent'
  | 'manual_research_queued' | 'manual_research_completed'
  | 'sync_failed' | 'sync_recovered';

export interface Activity {
  id: string;
  leadId: string;
  type: ActivityType;
  description: string;
  createdAt: string;
  createdBy: string;
  /** Optional metadata for structured events */
  metadata?: {
    channel?: string;
    mailbox?: string;
    twilioNumber?: string;
    apolloIdentity?: string;
    outcome?: string;
    duration?: number;
    handoffReason?: string;
    previousStage?: string;
    newStage?: string;
  };
}

// ─── Pipeline Configuration ──────────────────────────────

export const PIPELINE_LABELS: Record<Pipeline, string> = {
  'inbound': 'Inbound',
  'outbound-sdr': 'SDR Manual',
};

export const PIPELINE_DESCRIPTIONS: Record<Pipeline, string> = {
  'inbound': 'Incoming inquiries and booked conversations',
  'outbound-sdr': 'Outreach, replies, meetings, and client review',
};

export const PIPELINE_COLORS: Record<Pipeline, { bg: string; text: string; border: string; accent: string }> = {
  'inbound': { bg: 'bg-accent', text: 'text-accent-foreground', border: 'border-accent', accent: 'bg-accent-foreground' },
  'outbound-sdr': { bg: 'bg-primary/10', text: 'text-primary', border: 'border-primary/30', accent: 'bg-primary' },
};

// ─── Stage Configuration ─────────────────────────────────

export const INBOUND_STAGES: Stage[] = [
  'inbound-new', 'inbound-qualified', 'inbound-awaiting-sdr',
  'meeting-booked', 'inbound-disqualified', 'closed-lost',
];

export const SDR_STAGES: Stage[] = [
  'sdr-new-lead', 'sdr-contacted', 'sdr-replied',
  'meeting-booked', 'meeting-completed',
  'internal-decision', 'pricing-discussion',
  'trial-proposed', 'trial-active', 'payment-pending', 'converted', 'closed-lost',
];

export const SHARED_LIFECYCLE_STAGES: Stage[] = [
  'meeting-booked', 'meeting-completed',
  'internal-decision', 'pricing-discussion',
  'trial-proposed', 'trial-active',
  'payment-pending', 'converted', 'closed-lost',
];

export const PIPELINE_STAGES: Record<Pipeline, Stage[]> = {
  'inbound': INBOUND_STAGES,
  'outbound-sdr': SDR_STAGES,
};

export const STAGE_LABELS: Record<string, string> = {
  // Inbound
  'inbound-new': 'New Inquiry',
  'inbound-qualified': 'Replied',
  'inbound-awaiting-sdr': 'New Lead',
  'inbound-disqualified': 'Closed Lost',
  // SDR Manual
  'sdr-new-lead': 'New Lead',
  'sdr-contacted': 'Contacted',
  'sdr-replied': 'Replied',
  // Shared Commercial — new vocabulary
  'meeting-booked': 'Meeting Scheduled',
  'meeting-completed': 'Meeting Done',
  'internal-decision': 'Decision Pending',
  'pricing-discussion': 'Decision Pending',
  'trial-proposed': 'Moved to Client Review',
  'trial-active': 'Pilot',
  'payment-pending': 'Client Review',
  'converted': 'Active Client',
  'closed-lost': 'Closed Lost',
  'unsubscribed': 'Closed Lost',
  'cold-no-response': 'Cold',
  // Legacy compat
  'new-lead': 'New Lead',
  'contacted': 'Contacted',
  'replied': 'Replied',
  'new-inquiry': 'New Inquiry',
  'qualified': 'Qualified',
};

export const STAGE_GUIDANCE: Record<string, { meaning: string; nextStep: string }> = {
  'inbound-new': { meaning: 'Inbound inquiry received', nextStep: 'No outreach yet' },
  'inbound-qualified': { meaning: 'Conversation exists', nextStep: 'Schedule meeting' },
  'inbound-awaiting-sdr': { meaning: 'Waiting for SDR ownership', nextStep: 'No outreach yet' },
  'inbound-disqualified': { meaning: 'Closed lost', nextStep: 'Keep history' },
  'sdr-new-lead': { meaning: 'Fresh prospect', nextStep: 'No outreach yet' },
  'sdr-contacted': { meaning: 'Initial outreach happened', nextStep: 'No response yet' },
  'sdr-replied': { meaning: 'Conversation exists', nextStep: 'Schedule meeting' },
  'meeting-booked': { meaning: 'Meeting scheduled', nextStep: 'Meeting scheduled' },
  'meeting-completed': { meaning: 'Meeting happened', nextStep: 'Meeting result missing' },
  'internal-decision': { meaning: 'Client is deciding', nextStep: 'Awaiting decision' },
  'pricing-discussion': { meaning: 'Commercial discussion active', nextStep: 'Awaiting decision' },
  'trial-proposed': { meaning: 'Leadership review', nextStep: 'Client Review' },
  'trial-active': { meaning: 'Paid pilot', nextStep: 'Pilot decision' },
  'payment-pending': { meaning: 'Client review', nextStep: 'Verify payment and credentials' },
  'converted': { meaning: 'Active client', nextStep: 'Renewal continuity' },
  'closed-lost': { meaning: 'Closed lost', nextStep: 'Keep history' },
  'unsubscribed': { meaning: 'Contact unsubscribed', nextStep: 'Do not contact' },
  'cold-no-response': { meaning: 'Inactive but recoverable', nextStep: 'Cold' },
  // Legacy compat
  'new-lead': { meaning: 'New prospect', nextStep: 'No outreach yet' },
  'contacted': { meaning: 'Outreach sent', nextStep: 'No response yet' },
  'replied': { meaning: 'Lead replied', nextStep: 'Schedule meeting' },
  'new-inquiry': { meaning: 'Inbound inquiry', nextStep: 'No outreach yet' },
  'qualified': { meaning: 'Conversation ready', nextStep: 'Schedule meeting' },
};

export const STAGE_DEFAULT_ACTIONS: Record<string, string> = {
  'inbound-new': 'No outreach yet',
  'inbound-qualified': 'Schedule meeting',
  'inbound-awaiting-sdr': 'No outreach yet',
  'inbound-disqualified': 'Closed lost',
  'sdr-new-lead': 'No outreach yet',
  'sdr-contacted': 'No response yet',
  'sdr-replied': 'Schedule meeting',
  'meeting-booked': 'Meeting scheduled',
  'meeting-completed': 'Meeting result missing',
  'internal-decision': 'Follow up on internal review',
  'pricing-discussion': 'Awaiting decision',
  'trial-proposed': 'Client Review',
  'trial-active': 'Pilot',
  'payment-pending': 'Client Review',
  'converted': 'Active Client',
  'closed-lost': 'Add reason',
  'unsubscribed': 'Do not contact',
  'cold-no-response': 'Cold',
  // Legacy
  'new-lead': 'No outreach yet',
  'contacted': 'No response yet',
  'replied': 'Schedule meeting',
  'new-inquiry': 'No outreach yet',
  'qualified': 'Schedule meeting',
};

export const TRIAL_STAGES: Stage[] = ['trial-active'];
export const CONVERTED_STAGES: Stage[] = ['converted'];
export const PAYMENT_STAGES: Stage[] = ['payment-pending', 'converted'];
export const CLOSED_STAGES: Stage[] = ['closed-lost', 'inbound-disqualified', 'unsubscribed', 'cold-no-response'];
export const DEFAULT_STAGE: Record<Pipeline, Stage> = {
  'inbound': 'inbound-new',
  'outbound-sdr': 'sdr-new-lead',
};

export const FOLLOW_UP_DEFAULTS: Partial<Record<string, number>> = {
  'sdr-new-lead': 1, 'new-lead': 1,
  'sdr-contacted': 3, 'contacted': 3,
  'sdr-replied': 1, 'replied': 1,
  'meeting-booked': 0,
  'trial-proposed': 1,
  'trial-active': 7,
  'payment-pending': 1,
  'converted': 30,
};

// ─── Stage Family System ─────────────────────────────────

export type StageFamily = 'prospecting' | 'engagement' | 'meeting' | 'trial-prep' | 'trial' | 'payment' | 'customer' | 'closed';

export const STAGE_FAMILY: Record<string, StageFamily> = {
  // AI Outbound
  'ai-new-lead': 'prospecting', 'pending-enrichment': 'prospecting',
  'pending-apollo': 'prospecting', 'ready-for-outreach': 'prospecting',
  'email-sent-d0': 'prospecting', 'followup-1-d3': 'prospecting',
  'followup-2-d7': 'prospecting', 'followup-3-d14': 'prospecting',
  'round4-d17': 'prospecting',
  // Inbound
  'inbound-new': 'prospecting', 'inbound-qualified': 'engagement',
  'inbound-awaiting-sdr': 'engagement', 'inbound-disqualified': 'closed',
  // SDR Manual
  'sdr-new-lead': 'prospecting', 'sdr-contacted': 'prospecting',
  'sdr-replied': 'engagement',
  // Shared
  'meeting-booked': 'meeting', 'meeting-completed': 'meeting',
  'internal-decision': 'meeting', 'pricing-discussion': 'meeting',
  'trial-proposed': 'trial-prep', 'trial-active': 'trial',
  'payment-pending': 'payment', 'converted': 'customer', 'closed-lost': 'closed',
  'unsubscribed': 'closed', 'cold-no-response': 'closed',
  // Legacy
  'new-lead': 'prospecting', 'contacted': 'prospecting', 'lead-added': 'prospecting',
  'outreach-1': 'prospecting', 'outreach-2': 'prospecting', 'outreach-3': 'prospecting',
  'sequence-completed': 'prospecting', 'new-inquiry': 'prospecting',
  'replied': 'engagement', 'awaiting-sdr': 'engagement', 'qualified': 'engagement',
};

const FAMILY_ORDER: StageFamily[] = ['prospecting', 'engagement', 'meeting', 'trial-prep', 'trial', 'payment', 'customer', 'closed'];

const VALID_TASK_TYPES_PER_FAMILY: Record<StageFamily, DealTask['type'][]> = {
  'prospecting': ['follow-up', 'outreach', 'general'],
  'engagement': ['follow-up', 'general'],
  'meeting': ['meeting-prep', 'meeting-summary', 'follow-up', 'general'],
  'trial-prep': ['follow-up', 'general'],
  'trial': ['onboarding', 'check-in', 'conversion-push', 'trial-end', 'general'],
  'payment': ['payment', 'follow-up', 'general'],
  'customer': ['payment', 'general'],
  'closed': ['general'],
};

// ─── Deal Health (deprecated) ────────────────────────────

export type DealHealth = 'hot' | 'active' | 'at-risk' | 'cold';
export const DEAL_HEALTH_LABELS: Record<DealHealth, string> = { hot: 'On track', active: 'On track', 'at-risk': 'Follow up needed', cold: 'No response' };
export const DEAL_HEALTH_COLORS: Record<DealHealth, string> = { hot: 'bg-warning/15 text-warning border-warning/30', active: 'bg-success/15 text-success border-success/30', 'at-risk': 'bg-muted text-muted-foreground border-muted', cold: 'bg-muted text-muted-foreground border-muted' };
export function getDealHealth(_lead: Lead): DealHealth { return 'active'; }

// ─── Escalation System ──────────────────────────────────

export interface EscalationInfo {
  level: 'none' | 'warning' | 'overdue' | 'cold';
  message: string;
  daysSinceActivity: number;
}

export function getEscalation(lead: Lead): EscalationInfo {
  if (CONVERTED_STAGES.includes(lead.stage)) {
    if (lead.paymentStatus === 'overdue') {
      const days = getPaymentDaysUntilDue(lead);
      return { level: 'overdue', message: `Payment overdue${days ? ` by ${Math.abs(days)} days` : ''}`, daysSinceActivity: 0 };
    }
    return { level: 'none', message: '', daysSinceActivity: 0 };
  }
  if (CLOSED_STAGES.includes(lead.stage)) {
    return { level: 'none', message: '', daysSinceActivity: 0 };
  }
  if (lead.stage === 'payment-pending') {
    const days = getPaymentDaysUntilDue(lead);
    if (days !== null && days < -3) return { level: 'overdue', message: `Payment ${Math.abs(days)} days overdue`, daysSinceActivity: Math.abs(days) };
    if (days !== null && days < 0) return { level: 'warning', message: `Payment overdue`, daysSinceActivity: Math.abs(days) };
    return { level: 'none', message: '', daysSinceActivity: 0 };
  }
  const now = Date.now();
  const lastActivity = new Date(lead.lastContactedAt || lead.updatedAt).getTime();
  const days = Math.floor((now - lastActivity) / (1000 * 60 * 60 * 24));
  if (TRIAL_STAGES.includes(lead.stage)) {
    const daysLeft = getTrialDaysLeft(lead);
    if (daysLeft !== null && daysLeft <= 0) return { level: 'overdue', message: `Decision overdue`, daysSinceActivity: days };
    if (daysLeft !== null && daysLeft <= 3) return { level: 'warning', message: `Decision due in ${daysLeft} day${daysLeft > 1 ? 's' : ''}`, daysSinceActivity: days };
    return { level: 'none', message: '', daysSinceActivity: days };
  }
  if (days >= 7) return { level: 'cold', message: `No response for ${days} days`, daysSinceActivity: days };
  if (days >= 4) return { level: 'warning', message: `Follow-up due`, daysSinceActivity: days };
  return { level: 'none', message: '', daysSinceActivity: days };
}

// ─── Intelligent Next Actions ────────────────────────────

export interface IntelligentAction {
  action: string;
  reason: string;
  urgency: 'now' | 'today' | 'upcoming';
  followUpDate: string;
  channel?: string;
  deadline?: string;
}

export function recalculateNextAction(lead: Lead): IntelligentAction {
  const now = new Date();
  const addDays = (n: number) => { const d = new Date(now); d.setDate(d.getDate() + n); return d.toISOString(); };
  const stage = normalizeStage(lead.stage);

  switch (stage) {
    case 'sdr-new-lead': case 'new-lead':
      return { action: 'No outreach yet', reason: 'New lead', urgency: 'today', followUpDate: addDays(1), channel: 'email' };

    case 'sdr-contacted': case 'contacted': {
      const contacted = lead.lastContactedAt ? new Date(lead.lastContactedAt) : new Date(lead.updatedAt);
      const daysSince = Math.ceil((now.getTime() - contacted.getTime()) / (1000 * 60 * 60 * 24));
      if (daysSince >= 7) return { action: `No response for ${daysSince} days`, reason: 'No response yet', urgency: 'upcoming', followUpDate: addDays(1) };
      if (daysSince >= 3) return { action: `Follow-up due`, reason: `${daysSince} days since contact`, urgency: 'today', followUpDate: addDays(1), channel: 'phone' };
      return { action: `No response yet`, reason: 'Recently contacted', urgency: 'upcoming', followUpDate: addDays(3 - daysSince) };
    }

    case 'sdr-replied': case 'replied':
      return { action: 'Schedule meeting', reason: 'Reply received', urgency: 'today', followUpDate: addDays(1), channel: 'email' };

    case 'meeting-booked': {
      const meeting = lead.meetingNotes?.[lead.meetingNotes.length - 1];
      if (meeting && new Date(meeting.date) < now && !meeting.summary?.trim()) {
        return { action: 'Meeting result missing', reason: 'Meeting passed without outcome', urgency: 'today', followUpDate: now.toISOString() };
      }
      return { action: 'Meeting scheduled', reason: 'Business conversation scheduled', urgency: 'today', followUpDate: meeting?.date || addDays(1) };
    }

    case 'meeting-completed':
      return { action: 'Awaiting decision', reason: 'Meeting done', urgency: 'today', followUpDate: addDays(1) };

    case 'trial-proposed': {
      const needsApproval = !lead.approvedBy;
      const needsCreds = !hasValidCredentials(lead);
      if (needsApproval && needsCreds) return { action: 'Client Review', reason: 'Approval and credentials pending', urgency: 'today', followUpDate: now.toISOString() };
      if (needsApproval) return { action: 'Client Review', reason: 'Approval pending', urgency: 'today', followUpDate: now.toISOString() };
      if (needsCreds) return { action: 'Credentials missing', reason: 'Credentials pending', urgency: 'today', followUpDate: now.toISOString() };
      if ((lead.paymentStatus !== 'paid' && !lead.paymentReceivedAt) || !lead.paymentVerifiedAt) return { action: 'Verify payment', reason: 'Payment verification pending', urgency: 'today', followUpDate: now.toISOString() };
      return { action: 'Onboarding queue', reason: 'Ready for onboarding', urgency: 'today', followUpDate: addDays(1) };
    }

    case 'trial-active': {
      const daysLeft = getPilotDaysLeft(lead);
      if (daysLeft !== null) {
        if (daysLeft <= 0) return { action: 'Pilot decision due', reason: 'Move to Active Client or Lost', urgency: 'today', followUpDate: now.toISOString() };
        if (daysLeft <= 5) return { action: `Pilot ends in ${daysLeft} day${daysLeft > 1 ? 's' : ''}`, reason: 'Decision due soon', urgency: 'today', followUpDate: now.toISOString() };
      }
      return { action: 'Pilot active', reason: 'Paid pilot running', urgency: 'upcoming', followUpDate: addDays(7) };
    }

    case 'payment-pending': {
      const days = getPaymentDaysUntilDue(lead);
      if (days !== null && days < 0) return { action: `Payment ${Math.abs(days)} days overdue`, reason: 'Overdue', urgency: 'today', followUpDate: now.toISOString() };
      return { action: 'Awaiting payment', reason: 'Payment pending', urgency: 'today', followUpDate: addDays(1) };
    }

    case 'converted':
      return { action: 'Active client', reason: 'Recurring client', urgency: 'upcoming', followUpDate: addDays(30) };

    case 'closed-lost': case 'inbound-disqualified':
      return { action: 'Closed lost', reason: 'Closed', urgency: 'upcoming', followUpDate: addDays(90) };

    // Inbound stages
    case 'inbound-new': case 'new-inquiry':
      return { action: 'New inquiry', reason: 'Inbound lead', urgency: 'today', followUpDate: now.toISOString() };
    case 'inbound-qualified': case 'qualified':
      return { action: 'Schedule meeting', reason: 'Conversation ready', urgency: 'today', followUpDate: addDays(1) };
    case 'inbound-awaiting-sdr': case 'awaiting-sdr':
      return { action: 'No outreach yet', reason: 'Awaiting SDR', urgency: 'today', followUpDate: now.toISOString() };

    default:
      return { action: STAGE_DEFAULT_ACTIONS[lead.stage] || 'Review deal', reason: '', urgency: 'upcoming', followUpDate: addDays(1) };
  }
}

/**
 * Normalize legacy stage aliases to current SDR/Inbound stages.
 * COMPATIBILITY-ONLY — legacy AI-Outbound aliases are folded into their
 * SDR equivalents (matches store.ts AI_STAGE_MIGRATION). Safe to delete
 * after the legacy localStorage migration window closes.
 */
export function normalizeStage(stage: Stage): Stage {
  const MAP: Record<string, Stage> = {
    'new-lead': 'sdr-new-lead',
    'contacted': 'sdr-contacted',
    'replied': 'sdr-replied',
    'awaiting-sdr': 'inbound-awaiting-sdr',
    'new-inquiry': 'inbound-new',
    'qualified': 'inbound-qualified',
    // Legacy AI-Outbound stages → SDR equivalents
    'lead-added': 'sdr-new-lead',
    'ai-new-lead': 'sdr-new-lead',
    'pending-enrichment': 'sdr-new-lead',
    'pending-apollo': 'sdr-new-lead',
    'ready-for-outreach': 'sdr-new-lead',
    'email-sent-d0': 'sdr-contacted',
    'followup-1-d3': 'sdr-contacted',
    'followup-2-d7': 'sdr-contacted',
    'followup-3-d14': 'sdr-contacted',
    'round4-d17': 'sdr-contacted',
    'sequence-completed': 'sdr-contacted',
    'outreach-1': 'sdr-contacted',
    'outreach-2': 'sdr-contacted',
    'outreach-3': 'sdr-contacted',
  };
  return MAP[stage] || stage;
}

/** Get all contacts for a lead as BrandContact[] (unifies primary + secondary + contacts array) */
export function getLeadContacts(lead: Lead): BrandContact[] {
  // Start with explicit contacts array
  if (lead.contacts && lead.contacts.length > 0) return lead.contacts;
  // Build from legacy fields — and auto-populate contacts[] for future use
  const contacts: BrandContact[] = [];
  if (lead.contactName) {
    contacts.push({
      id: `${lead.id}-primary`,
      name: lead.contactName,
      role: lead.contactRole,
      email: lead.contactEmail,
      phone: lead.contactPhone,
      linkedin: lead.linkedin,
      instagram: lead.instagram,
      reached: false,
    });
  }
  if (lead.secondaryContact?.name) {
    contacts.push({
      id: `${lead.id}-secondary`,
      name: lead.secondaryContact.name,
      role: lead.secondaryContact.role,
      email: lead.secondaryContact.email,
      phone: lead.secondaryContact.phone,
      linkedin: lead.secondaryContact.linkedin,
      instagram: lead.secondaryContact.instagram,
      reached: false,
    });
  }
  return contacts;
}

/** Count contacts added to a brand */
export function getContactCount(lead: Lead): number {
  return getLeadContacts(lead).length;
}

export function getEntryFlow(lead: Lead): EntryFlow {
  if (lead.entry_flow) return lead.entry_flow;
  if (lead.pipeline === 'inbound') return 'inbound';
  return 'sdr_manual';
}

/** Check if stage is in the shared commercial lifecycle */
export function isSharedLifecycleStage(stage: Stage): boolean {
  return SHARED_LIFECYCLE_STAGES.includes(stage);
}

// ─── Revenue Intelligence ────────────────────────────────

export const PLAN_PRICES: Record<SubscriptionPlan, number> = {
  lite: 49, starter: 99, growth: 249, enterprise: 499, custom: 0,
};

export const CURRENCY_SYMBOL: Record<Currency, string> = {
  PKR: '₨', USD: '$', GBP: '£', AED: 'AED ',
};

export const CURRENCY_LABELS: Record<Currency, string> = {
  PKR: 'PKR', USD: 'USD', GBP: 'GBP', AED: 'AED',
};

export const REGION_LABELS: Record<Region, string> = {
  PK: 'Pakistan', US: 'United States', UK: 'United Kingdom', UAE: 'UAE', OTHER: 'Other',
};

/** Format a money amount with a currency symbol. */
export function formatMoney(amount: number, currency: Currency = 'USD'): string {
  const sym = CURRENCY_SYMBOL[currency] ?? '';
  const rounded = Math.round(amount).toLocaleString();
  return `${sym}${rounded}`;
}

/** Active commercial truth — falls back to proposed/legacy plan price. */
export function getActiveDeal(lead: Lead): { package: SubscriptionPlan; currency: Currency; value: number } {
  const pkg = lead.active_package ?? lead.proposed_package ?? lead.subscriptionPlan ?? 'starter';
  const currency = lead.active_currency ?? lead.proposed_currency ?? 'USD';
  const value = lead.active_value
    ?? lead.proposed_value
    ?? PLAN_PRICES[pkg as SubscriptionPlan]
    ?? PLAN_PRICES.starter;
  return { package: pkg, currency, value };
}

/** Proposed deal terms — used by CEO Review surface. */
export function getProposedDeal(lead: Lead): { package: SubscriptionPlan; currency: Currency; value: number } {
  const pkg = lead.proposed_package ?? lead.subscriptionPlan ?? 'starter';
  const currency = lead.proposed_currency ?? 'USD';
  const value = lead.proposed_value
    ?? PLAN_PRICES[pkg as SubscriptionPlan]
    ?? PLAN_PRICES.starter;
  return { package: pkg, currency, value };
}

// ─── Payment Ledger ──────────────────────────────────────

export type LedgerStatus = 'unpaid' | 'paid' | 'overdue';

export interface PaymentLedgerEntry {
  id: string;
  /** YYYY-MM, e.g. '2026-05' — billing month */
  billingMonth: string;
  amount: number;
  currency: Currency;
  dueDate: string;
  status: LedgerStatus;
  paidAt?: string;
  paidBy?: string;
  reference?: string;
  notes?: string;
}

export function getRevenueMetrics(leads: Lead[]) {
  const paying = leads.filter(l => CONVERTED_STAGES.includes(l.stage) && l.paymentStatus === 'paid');
  const pendingPayment = leads.filter(l => l.stage === 'payment-pending' || l.paymentStatus === 'pending');
  const overdue = leads.filter(l => l.paymentStatus === 'overdue' || l.paymentStatus === 'at-risk');
  const activeTrials = leads.filter(l => TRIAL_STAGES.includes(l.stage));
  const valueOf = (l: Lead) => getActiveDeal(l).value;
  const paidRevenue = paying.reduce((sum, l) => sum + valueOf(l), 0);
  const expectedRevenue = paidRevenue + pendingPayment.reduce((sum, l) => sum + valueOf(l), 0) + activeTrials.reduce((sum, l) => sum + valueOf(l), 0);
  const outstandingPayments = overdue.reduce((sum, l) => sum + valueOf(l), 0);
  return { paidRevenue, expectedRevenue, outstandingPayments, atRiskCount: overdue.length, activeCustomers: paying.length, pendingCount: pendingPayment.length };
}

// State cleanup
export function refreshTasksForStage(lead: Lead, newStage?: Stage): DealTask[] {
  const targetStage = newStage || lead.stage;
  const targetFamily = STAGE_FAMILY[targetStage] || 'prospecting';
  const targetFamilyIdx = FAMILY_ORDER.indexOf(targetFamily);
  const validTypes = VALID_TASK_TYPES_PER_FAMILY[targetFamily] || ['general'];
  return (lead.tasks || []).map(task => {
    if (task.completed || task.state === 'cancelled' || !task.autoGenerated) return task;
    if (validTypes.includes(task.type)) return task;
    const taskFamily = task.stageFamily ? task.stageFamily as StageFamily : undefined;
    if (taskFamily) {
      const taskFamilyIdx = FAMILY_ORDER.indexOf(taskFamily);
      if (taskFamilyIdx < targetFamilyIdx) {
        return { ...task, state: 'cancelled' as TaskState, completed: true, cancelledAt: new Date().toISOString(), cancelReason: `Auto-cancelled: deal moved to ${STAGE_LABELS[targetStage] || targetStage}` };
      }
    }
    return { ...task, state: 'cancelled' as TaskState, completed: true, cancelledAt: new Date().toISOString(), cancelReason: `Auto-cancelled: not relevant for ${STAGE_LABELS[targetStage] || targetStage}` };
  });
}

export function completeAction(lead: Lead, action: string, completedBy: string, channel?: string, notes?: string): Lead {
  const completion: ActionCompletion = { id: crypto.randomUUID(), action, completedAt: new Date().toISOString(), completedBy, channel, notes };
  const now = new Date().toISOString();
  const timingUpdates: Partial<Lead> = {};
  const actionLower = action.toLowerCase();
  if (channel === 'email' || actionLower.includes('email')) timingUpdates.lastEmailAt = now;
  if (channel === 'linkedin' || actionLower.includes('linkedin')) timingUpdates.lastLinkedinAt = now;
  if (channel === 'phone' || actionLower.includes('call')) timingUpdates.lastCallAt = now;
  if (actionLower.includes('replied') || actionLower.includes('response')) timingUpdates.lastReplyAt = now;
  const updated: Lead = { ...lead, ...timingUpdates, lastContactedAt: now, updatedAt: now, actionCompletions: [...(lead.actionCompletions || []), completion] };
  const intel = recalculateNextAction(updated);
  return { ...updated, nextAction: intel.action, nextActionReason: intel.reason, nextActionUrgency: intel.urgency, nextFollowUp: intel.followUpDate };
}

// ─── Plans & Labels ──────────────────────────────────────

export const PLAN_LABELS: Record<SubscriptionPlan, string> = { lite: 'Lite', starter: 'Starter', growth: 'Growth', enterprise: 'Enterprise', custom: 'Custom' };
export const PLATFORM_LABELS: Record<Platform, string> = { shopify: 'Shopify', woocommerce: 'WooCommerce', custom: 'Custom' };
export const PAYMENT_STATUS_LABELS: Record<PaymentStatus, string> = { pending: 'Pending', paid: 'Paid', overdue: 'Overdue', 'at-risk': 'At Risk' };
export const LEAD_SOURCE_LABELS: Record<LeadSource, string> = { instagram: 'Instagram', google: 'Google', linkedin: 'LinkedIn', referral: 'Referral', website: 'Website', other: 'Other' };
export const LEAD_TIER_LABELS: Record<LeadTier, string> = { 'tier-1': 'Tier 1', 'tier-2': 'Tier 2', 'tier-3': 'Tier 3' };
export const LEAD_PRIORITY_LABELS: Record<LeadPriority, string> = { high: 'High', medium: 'Medium', low: 'Low' };
export const SMARTLEAD_STATUS_LABELS: Record<SmartleadStatus, string> = { assigned: 'Assigned', opened: 'Opened', replied: 'Replied', 'no-response': 'No Response', completed: 'Completed' };

export const ENTRY_FLOW_LABELS: Record<EntryFlow, string> = { inbound: 'Inbound', sdr_manual: 'SDR Manual' };
export const INBOUND_TYPE_LABELS: Record<string, string> = { ai_inbound: 'Website Inquiry', direct_book_demo: 'Demo Booking', manual_inbound: 'Manual Inbound' };
export const SOURCE_DETAIL_LABELS: Record<SourceDetail, string> = {
  instagram: 'Instagram', google_search: 'Google Search', linkedin_evaboot: 'LinkedIn/Evaboot',
  website_demo: 'Website Demo', website_form: 'Website Form', whatsapp: 'WhatsApp',
  instagram_dm: 'Instagram DM', linkedin_dm: 'LinkedIn DM', email_inbound: 'Email Inbound',
  ai_chatbot: 'Website Chat', referral: 'Referral', manual_import: 'Manual Import', other: 'Other',
};

// ─── Team ────────────────────────────────────────────────

export type TeamMemberLite = { id: string; name: string; role: string; region: string };

/** Static seed used as fallback if no employee store data exists yet (SSR / first paint). */
const SEED_TEAM_MEMBERS: TeamMemberLite[] = [
  { id: 'abdullah', name: 'Abdullah - CEO', role: 'CEO', region: '' },
  { id: 'hira', name: 'Hira - COO', role: 'COO', region: '' },
  { id: 'namra', name: 'Namra - Operations', role: 'Operations', region: '' },
  { id: 'muneeb', name: 'Muneeb', role: 'Onboarding', region: '' },
  { id: 'areeba', name: 'Areeba', role: 'SDR', region: 'USA' },
  { id: 'taiba', name: 'Taiba', role: 'SDR', region: 'UK' },
  { id: 'khadija', name: 'Khadija', role: 'SDR', region: 'Pakistan' },
  { id: 'asjad', name: 'Asjad', role: 'SDR', region: 'Pakistan' },
  { id: 'mashael', name: 'Mashael', role: 'SDR', region: 'UAE' },
];

/**
 * Live team roster — rebuilt in-place from the employee-store's persisted profiles
 * so that newly added / deactivated teammates immediately appear in legacy
 * dropdowns and lookups that import these arrays as static module values.
 *
 * Always exported as the SAME array reference so existing imports keep working.
 */
export const TEAM_MEMBERS: TeamMemberLite[] = [...SEED_TEAM_MEMBERS];
export const SALES_MEMBERS: TeamMemberLite[] = TEAM_MEMBERS.filter(m => m.role === 'SDR');
export const APPROVAL_MEMBERS: TeamMemberLite[] = TEAM_MEMBERS.filter(m => m.role === 'CEO' || m.role === 'COO');
export const SDR_IDS: string[] = SALES_MEMBERS.map(m => m.id);

/** Monotonically increases each time the team arrays are rebuilt. Components
 *  that memoize on team data can subscribe via `subscribeTeamRoster` and use
 *  this version as a dependency to invalidate caches. */
let teamRosterVersion = 0;
const teamRosterListeners = new Set<() => void>();
export function getTeamRosterVersion(): number { return teamRosterVersion; }
export function subscribeTeamRoster(fn: () => void): () => void {
  teamRosterListeners.add(fn);
  return () => { teamRosterListeners.delete(fn); };
}
function emitTeamRosterChange(): void {
  teamRosterVersion++;
  teamRosterListeners.forEach(fn => { try { fn(); } catch { /* ignore */ } });
  try {
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new CustomEvent('stylique:team-roster-updated', { detail: { version: teamRosterVersion } }));
    }
  } catch { /* ignore */ }
}

function normalizeRole(r: string): string {
  const lc = (r || '').toLowerCase();
  if (lc === 'ceo') return 'CEO';
  if (lc === 'coo') return 'COO';
  if (lc === 'operations') return 'Operations';
  if (lc === 'onboarding') return 'Onboarding';
  return 'SDR';
}

/** Rebuild the exported team arrays in-place from a list of employee-like records. */
export function setTeamMembersFromEmployees(
  employees: Array<{ id: string; fullName?: string; name?: string; role: string; region?: string; active?: boolean }>
): void {
  const next: TeamMemberLite[] = employees
    .filter(e => e.active !== false)
    .map(e => ({
      id: e.id,
      name: e.fullName || e.name || e.id,
      role: normalizeRole(e.role),
      region: e.region || '',
    }));
  if (next.length === 0) return; // never wipe to empty
  TEAM_MEMBERS.length = 0; TEAM_MEMBERS.push(...next);
  SALES_MEMBERS.length = 0; SALES_MEMBERS.push(...next.filter(m => m.role === 'SDR'));
  APPROVAL_MEMBERS.length = 0; APPROVAL_MEMBERS.push(...next.filter(m => m.role === 'CEO' || m.role === 'COO'));
  SDR_IDS.length = 0; SDR_IDS.push(...SALES_MEMBERS.map(m => m.id));
  emitTeamRosterChange();
}

/** Read persisted employees from localStorage and rebuild team arrays. Safe to call at module init. */
export function syncTeamMembersFromStorage(): void {
  try {
    if (typeof window === 'undefined' || !window.localStorage) return;
    const raw = window.localStorage.getItem('stylique-employees');
    if (!raw) return;
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed) && parsed.length > 0) setTeamMembersFromEmployees(parsed);
  } catch { /* ignore */ }
}

// Eagerly hydrate from localStorage so first paint sees added/edited teammates.
syncTeamMembersFromStorage();

export const REGION_COLORS: Record<string, string> = {
  'USA': 'bg-blue-500/15 text-blue-400',
  'UK': 'bg-emerald-500/15 text-emerald-400',
  'Pakistan': 'bg-amber-500/15 text-amber-400',
  'UAE': 'bg-rose-500/15 text-rose-400',
};

// ─── Helpers ─────────────────────────────────────────────

export function getTrialDaysLeft(lead: Lead): number | null {
  if (!lead.trialEndDate) return null;
  return Math.ceil((new Date(lead.trialEndDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24));
}

export function getPilotDaysLeft(lead: Lead): number | null {
  const end = lead.pilotEndDate || lead.trialEndDate;
  if (!end) return null;
  return Math.ceil((new Date(end).getTime() - Date.now()) / (1000 * 60 * 60 * 24));
}

export function getTrialMilestone(lead: Lead): { label: string; urgency: 'normal' | 'warning' | 'overdue' } | null {
  const days = getPilotDaysLeft(lead);
  if (days === null) return null;
  if (days <= 0) return { label: 'Decision overdue', urgency: 'overdue' };
  if (days <= 2) return { label: `Decision due in ${days} day${days > 1 ? 's' : ''}`, urgency: 'overdue' };
  if (days <= 5) return { label: `Pilot ends in ${days} days`, urgency: 'warning' };
  if (days <= 7) return { label: `${days} days left`, urgency: 'warning' };
  return { label: `${days} days left`, urgency: 'normal' };
}

export function generateTrialTasks(lead: Lead): DealTask[] {
  if (!lead.trialStartDate || !lead.trialEndDate) return [];
  const start = new Date(lead.trialStartDate);
  const uid = () => crypto.randomUUID();
  const now = new Date().toISOString();
  const day = (n: number) => { const d = new Date(start); d.setDate(d.getDate() + n); return d.toISOString(); };
  return [
    { id: uid(), title: `Done & verified for ${lead.companyName}`, dueDate: day(0), completed: false, assignedTo: 'muneeb', type: 'onboarding', autoGenerated: true, createdAt: now, priority: 'medium', reason: 'Onboarding verification', stageFamily: 'onboarding' },
  ];
}

export function getPaymentDaysUntilDue(lead: Lead): number | null {
  if (!lead.nextPaymentDate) return null;
  return Math.ceil((new Date(lead.nextPaymentDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24));
}

export function getPaymentAlert(lead: Lead): { label: string; urgency: 'normal' | 'warning' | 'overdue' } | null {
  const days = getPaymentDaysUntilDue(lead);
  if (days === null) return null;
  if (days <= -5) return { label: `Payment ${Math.abs(days)} days overdue`, urgency: 'overdue' };
  if (days <= -1) return { label: 'Payment overdue', urgency: 'overdue' };
  if (days <= 2) return { label: `Payment due in ${days} day${days > 1 ? 's' : ''}`, urgency: 'warning' };
  if (days <= 5) return { label: `Payment due in ${days} days`, urgency: 'warning' };
  return null;
}

export function getDefaultFollowUpDate(stage: Stage): string | undefined {
  const days = FOLLOW_UP_DEFAULTS[stage];
  if (days === undefined) return undefined;
  const d = new Date(); d.setDate(d.getDate() + days); return d.toISOString();
}

export function getContactFieldCount(lead: Partial<Lead>): number {
  let count = 0;
  if (lead.contactEmail?.trim()) count++;
  if (lead.contactPhone?.trim()) count++;
  if (lead.website?.trim()) count++;
  if (lead.instagram?.trim()) count++;
  if (lead.linkedin?.trim()) count++;
  return count;
}

export function isCeoOrCoo(memberId: string): boolean {
  const m = TEAM_MEMBERS.find(t => t.id === memberId);
  return m?.role === 'CEO' || m?.role === 'COO';
}

export function isViewAllMember(memberId: string): boolean {
  const m = TEAM_MEMBERS.find(t => t.id === memberId);
  return m?.role === 'CEO' || m?.role === 'COO' || m?.role === 'Operations';
}

export function isSDR(memberId: string): boolean {
  return SDR_IDS.includes(memberId);
}

export function hasValidCredentials(lead: Lead): boolean {
  if (lead.credentials?.username && lead.credentials?.password) return true;
  if (lead.storeCredentials?.trim()) return true;
  return false;
}

export function getTaskPriority(task: DealTask): TaskPriority {
  if (task.priority) return task.priority;
  const now = Date.now();
  const due = new Date(task.dueDate).getTime();
  if (due < now) return 'critical';
  const hoursUntil = (due - now) / (1000 * 60 * 60);
  if (hoursUntil < 24) return 'high';
  if (hoursUntil < 72) return 'medium';
  return 'low';
}

export function getTaskUrgencyLabel(task: DealTask): { label: string; color: string } {
  const p = getTaskPriority(task);
  switch (p) {
    case 'critical': return { label: 'Do now', color: 'text-destructive' };
    case 'high': return { label: 'Due today', color: 'text-foreground' };
    case 'medium': return { label: 'Next step', color: 'text-muted-foreground' };
    case 'low': return { label: 'Later', color: 'text-muted-foreground/60' };
  }
}

export function getActiveTasks(tasks: DealTask[]): DealTask[] {
  return tasks.filter(t => !t.completed && t.state !== 'cancelled');
}

export function getPendingTaskCount(lead: Lead): number {
  return getActiveTasks(lead.tasks || []).length;
}
